// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/pos-service/internal/ent/appointment"
	"github.com/bengobox/pos-service/internal/ent/auditlog"
	"github.com/bengobox/pos-service/internal/ent/backup"
	"github.com/bengobox/pos-service/internal/ent/backupsetting"
	"github.com/bengobox/pos-service/internal/ent/bartab"
	"github.com/bengobox/pos-service/internal/ent/bartabevent"
	"github.com/bengobox/pos-service/internal/ent/billsplit"
	"github.com/bengobox/pos-service/internal/ent/cashdrawer"
	"github.com/bengobox/pos-service/internal/ent/cashdrawerevent"
	"github.com/bengobox/pos-service/internal/ent/channelintegration"
	"github.com/bengobox/pos-service/internal/ent/channelsyncjob"
	"github.com/bengobox/pos-service/internal/ent/clientrecord"
	"github.com/bengobox/pos-service/internal/ent/commissionrecord"
	"github.com/bengobox/pos-service/internal/ent/commissionrule"
	"github.com/bengobox/pos-service/internal/ent/customerbalancecache"
	"github.com/bengobox/pos-service/internal/ent/dailyclosing"
	"github.com/bengobox/pos-service/internal/ent/documentsequence"
	"github.com/bengobox/pos-service/internal/ent/eventbooking"
	"github.com/bengobox/pos-service/internal/ent/facility"
	"github.com/bengobox/pos-service/internal/ent/facilitybooking"
	"github.com/bengobox/pos-service/internal/ent/featureoverride"
	"github.com/bengobox/pos-service/internal/ent/giftcard"
	"github.com/bengobox/pos-service/internal/ent/giftcardtransaction"
	"github.com/bengobox/pos-service/internal/ent/helditem"
	"github.com/bengobox/pos-service/internal/ent/housekeepingtask"
	"github.com/bengobox/pos-service/internal/ent/idempotencykey"
	"github.com/bengobox/pos-service/internal/ent/integrationsetting"
	"github.com/bengobox/pos-service/internal/ent/inventorysnapshot"
	"github.com/bengobox/pos-service/internal/ent/kdsstation"
	"github.com/bengobox/pos-service/internal/ent/kdssyncfailure"
	"github.com/bengobox/pos-service/internal/ent/kdsticket"
	"github.com/bengobox/pos-service/internal/ent/layawaypayment"
	"github.com/bengobox/pos-service/internal/ent/layawayplan"
	"github.com/bengobox/pos-service/internal/ent/leaverequest"
	"github.com/bengobox/pos-service/internal/ent/licenseusagesnapshot"
	"github.com/bengobox/pos-service/internal/ent/loyaltyaccount"
	"github.com/bengobox/pos-service/internal/ent/loyaltyprogram"
	"github.com/bengobox/pos-service/internal/ent/loyaltytransaction"
	"github.com/bengobox/pos-service/internal/ent/mealentitlement"
	"github.com/bengobox/pos-service/internal/ent/modifier"
	"github.com/bengobox/pos-service/internal/ent/modifiergroup"
	"github.com/bengobox/pos-service/internal/ent/orderlink"
	"github.com/bengobox/pos-service/internal/ent/ordervoidcode"
	"github.com/bengobox/pos-service/internal/ent/outboxevent"
	"github.com/bengobox/pos-service/internal/ent/outlet"
	"github.com/bengobox/pos-service/internal/ent/outletsetting"
	"github.com/bengobox/pos-service/internal/ent/poscatalogoverride"
	"github.com/bengobox/pos-service/internal/ent/posdevice"
	"github.com/bengobox/pos-service/internal/ent/posdevicesession"
	"github.com/bengobox/pos-service/internal/ent/poslinemodifier"
	"github.com/bengobox/pos-service/internal/ent/posnotification"
	"github.com/bengobox/pos-service/internal/ent/posorder"
	"github.com/bengobox/pos-service/internal/ent/posorderevent"
	"github.com/bengobox/pos-service/internal/ent/posorderline"
	"github.com/bengobox/pos-service/internal/ent/pospayment"
	"github.com/bengobox/pos-service/internal/ent/pospermission"
	"github.com/bengobox/pos-service/internal/ent/posrefund"
	"github.com/bengobox/pos-service/internal/ent/posreturn"
	"github.com/bengobox/pos-service/internal/ent/posreturnline"
	"github.com/bengobox/pos-service/internal/ent/posreversal"
	"github.com/bengobox/pos-service/internal/ent/posrole"
	"github.com/bengobox/pos-service/internal/ent/posrolepermission"
	"github.com/bengobox/pos-service/internal/ent/posrolev2"
	"github.com/bengobox/pos-service/internal/ent/possaleedit"
	"github.com/bengobox/pos-service/internal/ent/possaleshred"
	"github.com/bengobox/pos-service/internal/ent/posuserroleassignment"
	"github.com/bengobox/pos-service/internal/ent/pricebook"
	"github.com/bengobox/pos-service/internal/ent/pricebookitem"
	"github.com/bengobox/pos-service/internal/ent/printagent"
	"github.com/bengobox/pos-service/internal/ent/printjob"
	"github.com/bengobox/pos-service/internal/ent/promotion"
	"github.com/bengobox/pos-service/internal/ent/promotionapplication"
	"github.com/bengobox/pos-service/internal/ent/promotionredemption"
	"github.com/bengobox/pos-service/internal/ent/promotionrule"
	"github.com/bengobox/pos-service/internal/ent/ratelimitconfig"
	"github.com/bengobox/pos-service/internal/ent/referral"
	"github.com/bengobox/pos-service/internal/ent/repairjob"
	"github.com/bengobox/pos-service/internal/ent/repairjobevent"
	"github.com/bengobox/pos-service/internal/ent/repairjobpart"
	"github.com/bengobox/pos-service/internal/ent/resource"
	"github.com/bengobox/pos-service/internal/ent/room"
	"github.com/bengobox/pos-service/internal/ent/roomamenity"
	"github.com/bengobox/pos-service/internal/ent/roomamenityassignment"
	"github.com/bengobox/pos-service/internal/ent/roombooking"
	"github.com/bengobox/pos-service/internal/ent/roomfolioitem"
	"github.com/bengobox/pos-service/internal/ent/roomfoliopayment"
	"github.com/bengobox/pos-service/internal/ent/roomguest"
	"github.com/bengobox/pos-service/internal/ent/section"
	"github.com/bengobox/pos-service/internal/ent/serialnumberlog"
	"github.com/bengobox/pos-service/internal/ent/serviceconfig"
	"github.com/bengobox/pos-service/internal/ent/servicepackage"
	"github.com/bengobox/pos-service/internal/ent/servicepackagepurchase"
	"github.com/bengobox/pos-service/internal/ent/servicepackageredemption"
	"github.com/bengobox/pos-service/internal/ent/servicequeueentry"
	"github.com/bengobox/pos-service/internal/ent/shiftrotation"
	"github.com/bengobox/pos-service/internal/ent/shiftrotationslot"
	"github.com/bengobox/pos-service/internal/ent/staffadvance"
	"github.com/bengobox/pos-service/internal/ent/staffmember"
	"github.com/bengobox/pos-service/internal/ent/staffoutlet"
	"github.com/bengobox/pos-service/internal/ent/staffpayroll"
	"github.com/bengobox/pos-service/internal/ent/staffpayrollline"
	"github.com/bengobox/pos-service/internal/ent/staffpurchaselink"
	"github.com/bengobox/pos-service/internal/ent/staffschedule"
	"github.com/bengobox/pos-service/internal/ent/staffshiftoverride"
	"github.com/bengobox/pos-service/internal/ent/stockalertsubscription"
	"github.com/bengobox/pos-service/internal/ent/stockconsumptionevent"
	"github.com/bengobox/pos-service/internal/ent/syncfailure"
	"github.com/bengobox/pos-service/internal/ent/table"
	"github.com/bengobox/pos-service/internal/ent/tableassignment"
	"github.com/bengobox/pos-service/internal/ent/tablereservation"
	"github.com/bengobox/pos-service/internal/ent/tenant"
	"github.com/bengobox/pos-service/internal/ent/tenantsyncevent"
	"github.com/bengobox/pos-service/internal/ent/tender"
	"github.com/bengobox/pos-service/internal/ent/user"
	"github.com/bengobox/pos-service/internal/ent/userposrole"
	"github.com/bengobox/pos-service/internal/ent/webhookdelivery"
	"github.com/bengobox/pos-service/internal/ent/webhooksubscription"
	"github.com/bengobox/pos-service/internal/ent/weighingscalereading"
)

// ent aliases to avoid import conflicts in user's code.
type (
	Op            = ent.Op
	Hook          = ent.Hook
	Value         = ent.Value
	Query         = ent.Query
	QueryContext  = ent.QueryContext
	Querier       = ent.Querier
	QuerierFunc   = ent.QuerierFunc
	Interceptor   = ent.Interceptor
	InterceptFunc = ent.InterceptFunc
	Traverser     = ent.Traverser
	TraverseFunc  = ent.TraverseFunc
	Policy        = ent.Policy
	Mutator       = ent.Mutator
	Mutation      = ent.Mutation
	MutateFunc    = ent.MutateFunc
)

type clientCtxKey struct{}

// FromContext returns a Client stored inside a context, or nil if there isn't one.
func FromContext(ctx context.Context) *Client {
	c, _ := ctx.Value(clientCtxKey{}).(*Client)
	return c
}

// NewContext returns a new context with the given Client attached.
func NewContext(parent context.Context, c *Client) context.Context {
	return context.WithValue(parent, clientCtxKey{}, c)
}

type txCtxKey struct{}

// TxFromContext returns a Tx stored inside a context, or nil if there isn't one.
func TxFromContext(ctx context.Context) *Tx {
	tx, _ := ctx.Value(txCtxKey{}).(*Tx)
	return tx
}

// NewTxContext returns a new context with the given Tx attached.
func NewTxContext(parent context.Context, tx *Tx) context.Context {
	return context.WithValue(parent, txCtxKey{}, tx)
}

// OrderFunc applies an ordering on the sql selector.
// Deprecated: Use Asc/Desc functions or the package builders instead.
type OrderFunc func(*sql.Selector)

var (
	initCheck   sync.Once
	columnCheck sql.ColumnCheck
)

// checkColumn checks if the column exists in the given table.
func checkColumn(t, c string) error {
	initCheck.Do(func() {
		columnCheck = sql.NewColumnCheck(map[string]func(string) bool{
			appointment.Table:              appointment.ValidColumn,
			auditlog.Table:                 auditlog.ValidColumn,
			backup.Table:                   backup.ValidColumn,
			backupsetting.Table:            backupsetting.ValidColumn,
			bartab.Table:                   bartab.ValidColumn,
			bartabevent.Table:              bartabevent.ValidColumn,
			billsplit.Table:                billsplit.ValidColumn,
			cashdrawer.Table:               cashdrawer.ValidColumn,
			cashdrawerevent.Table:          cashdrawerevent.ValidColumn,
			channelintegration.Table:       channelintegration.ValidColumn,
			channelsyncjob.Table:           channelsyncjob.ValidColumn,
			clientrecord.Table:             clientrecord.ValidColumn,
			commissionrecord.Table:         commissionrecord.ValidColumn,
			commissionrule.Table:           commissionrule.ValidColumn,
			customerbalancecache.Table:     customerbalancecache.ValidColumn,
			dailyclosing.Table:             dailyclosing.ValidColumn,
			documentsequence.Table:         documentsequence.ValidColumn,
			eventbooking.Table:             eventbooking.ValidColumn,
			facility.Table:                 facility.ValidColumn,
			facilitybooking.Table:          facilitybooking.ValidColumn,
			featureoverride.Table:          featureoverride.ValidColumn,
			giftcard.Table:                 giftcard.ValidColumn,
			giftcardtransaction.Table:      giftcardtransaction.ValidColumn,
			helditem.Table:                 helditem.ValidColumn,
			housekeepingtask.Table:         housekeepingtask.ValidColumn,
			idempotencykey.Table:           idempotencykey.ValidColumn,
			integrationsetting.Table:       integrationsetting.ValidColumn,
			inventorysnapshot.Table:        inventorysnapshot.ValidColumn,
			kdsstation.Table:               kdsstation.ValidColumn,
			kdssyncfailure.Table:           kdssyncfailure.ValidColumn,
			kdsticket.Table:                kdsticket.ValidColumn,
			layawaypayment.Table:           layawaypayment.ValidColumn,
			layawayplan.Table:              layawayplan.ValidColumn,
			leaverequest.Table:             leaverequest.ValidColumn,
			licenseusagesnapshot.Table:     licenseusagesnapshot.ValidColumn,
			loyaltyaccount.Table:           loyaltyaccount.ValidColumn,
			loyaltyprogram.Table:           loyaltyprogram.ValidColumn,
			loyaltytransaction.Table:       loyaltytransaction.ValidColumn,
			mealentitlement.Table:          mealentitlement.ValidColumn,
			modifier.Table:                 modifier.ValidColumn,
			modifiergroup.Table:            modifiergroup.ValidColumn,
			orderlink.Table:                orderlink.ValidColumn,
			ordervoidcode.Table:            ordervoidcode.ValidColumn,
			outboxevent.Table:              outboxevent.ValidColumn,
			outlet.Table:                   outlet.ValidColumn,
			outletsetting.Table:            outletsetting.ValidColumn,
			poscatalogoverride.Table:       poscatalogoverride.ValidColumn,
			posdevice.Table:                posdevice.ValidColumn,
			posdevicesession.Table:         posdevicesession.ValidColumn,
			poslinemodifier.Table:          poslinemodifier.ValidColumn,
			posorder.Table:                 posorder.ValidColumn,
			posorderevent.Table:            posorderevent.ValidColumn,
			posorderline.Table:             posorderline.ValidColumn,
			pospayment.Table:               pospayment.ValidColumn,
			pospermission.Table:            pospermission.ValidColumn,
			posrefund.Table:                posrefund.ValidColumn,
			posreturn.Table:                posreturn.ValidColumn,
			posreturnline.Table:            posreturnline.ValidColumn,
			posreversal.Table:              posreversal.ValidColumn,
			posrole.Table:                  posrole.ValidColumn,
			posrolepermission.Table:        posrolepermission.ValidColumn,
			posrolev2.Table:                posrolev2.ValidColumn,
			possaleedit.Table:              possaleedit.ValidColumn,
			possaleshred.Table:             possaleshred.ValidColumn,
			posuserroleassignment.Table:    posuserroleassignment.ValidColumn,
			posnotification.Table:          posnotification.ValidColumn,
			pricebook.Table:                pricebook.ValidColumn,
			pricebookitem.Table:            pricebookitem.ValidColumn,
			printagent.Table:               printagent.ValidColumn,
			printjob.Table:                 printjob.ValidColumn,
			promotion.Table:                promotion.ValidColumn,
			promotionapplication.Table:     promotionapplication.ValidColumn,
			promotionredemption.Table:      promotionredemption.ValidColumn,
			promotionrule.Table:            promotionrule.ValidColumn,
			ratelimitconfig.Table:          ratelimitconfig.ValidColumn,
			referral.Table:                 referral.ValidColumn,
			repairjob.Table:                repairjob.ValidColumn,
			repairjobevent.Table:           repairjobevent.ValidColumn,
			repairjobpart.Table:            repairjobpart.ValidColumn,
			resource.Table:                 resource.ValidColumn,
			room.Table:                     room.ValidColumn,
			roomamenity.Table:              roomamenity.ValidColumn,
			roomamenityassignment.Table:    roomamenityassignment.ValidColumn,
			roombooking.Table:              roombooking.ValidColumn,
			roomfolioitem.Table:            roomfolioitem.ValidColumn,
			roomfoliopayment.Table:         roomfoliopayment.ValidColumn,
			roomguest.Table:                roomguest.ValidColumn,
			section.Table:                  section.ValidColumn,
			serialnumberlog.Table:          serialnumberlog.ValidColumn,
			serviceconfig.Table:            serviceconfig.ValidColumn,
			servicepackage.Table:           servicepackage.ValidColumn,
			servicepackagepurchase.Table:   servicepackagepurchase.ValidColumn,
			servicepackageredemption.Table: servicepackageredemption.ValidColumn,
			servicequeueentry.Table:        servicequeueentry.ValidColumn,
			shiftrotation.Table:            shiftrotation.ValidColumn,
			shiftrotationslot.Table:        shiftrotationslot.ValidColumn,
			staffadvance.Table:             staffadvance.ValidColumn,
			staffmember.Table:              staffmember.ValidColumn,
			staffoutlet.Table:              staffoutlet.ValidColumn,
			staffpayroll.Table:             staffpayroll.ValidColumn,
			staffpayrollline.Table:         staffpayrollline.ValidColumn,
			staffpurchaselink.Table:        staffpurchaselink.ValidColumn,
			staffschedule.Table:            staffschedule.ValidColumn,
			staffshiftoverride.Table:       staffshiftoverride.ValidColumn,
			stockalertsubscription.Table:   stockalertsubscription.ValidColumn,
			stockconsumptionevent.Table:    stockconsumptionevent.ValidColumn,
			syncfailure.Table:              syncfailure.ValidColumn,
			table.Table:                    table.ValidColumn,
			tableassignment.Table:          tableassignment.ValidColumn,
			tablereservation.Table:         tablereservation.ValidColumn,
			tenant.Table:                   tenant.ValidColumn,
			tenantsyncevent.Table:          tenantsyncevent.ValidColumn,
			tender.Table:                   tender.ValidColumn,
			user.Table:                     user.ValidColumn,
			userposrole.Table:              userposrole.ValidColumn,
			webhookdelivery.Table:          webhookdelivery.ValidColumn,
			webhooksubscription.Table:      webhooksubscription.ValidColumn,
			weighingscalereading.Table:     weighingscalereading.ValidColumn,
		})
	})
	return columnCheck(t, c)
}

// Asc applies the given fields in ASC order.
func Asc(fields ...string) func(*sql.Selector) {
	return func(s *sql.Selector) {
		for _, f := range fields {
			if err := checkColumn(s.TableName(), f); err != nil {
				s.AddError(&ValidationError{Name: f, err: fmt.Errorf("ent: %w", err)})
			}
			s.OrderBy(sql.Asc(s.C(f)))
		}
	}
}

// Desc applies the given fields in DESC order.
func Desc(fields ...string) func(*sql.Selector) {
	return func(s *sql.Selector) {
		for _, f := range fields {
			if err := checkColumn(s.TableName(), f); err != nil {
				s.AddError(&ValidationError{Name: f, err: fmt.Errorf("ent: %w", err)})
			}
			s.OrderBy(sql.Desc(s.C(f)))
		}
	}
}

// AggregateFunc applies an aggregation step on the group-by traversal/selector.
type AggregateFunc func(*sql.Selector) string

// As is a pseudo aggregation function for renaming another other functions with custom names. For example:
//
//	GroupBy(field1, field2).
//	Aggregate(ent.As(ent.Sum(field1), "sum_field1"), (ent.As(ent.Sum(field2), "sum_field2")).
//	Scan(ctx, &v)
func As(fn AggregateFunc, end string) AggregateFunc {
	return func(s *sql.Selector) string {
		return sql.As(fn(s), end)
	}
}

// Count applies the "count" aggregation function on each group.
func Count() AggregateFunc {
	return func(s *sql.Selector) string {
		return sql.Count("*")
	}
}

// Max applies the "max" aggregation function on the given field of each group.
func Max(field string) AggregateFunc {
	return func(s *sql.Selector) string {
		if err := checkColumn(s.TableName(), field); err != nil {
			s.AddError(&ValidationError{Name: field, err: fmt.Errorf("ent: %w", err)})
			return ""
		}
		return sql.Max(s.C(field))
	}
}

// Mean applies the "mean" aggregation function on the given field of each group.
func Mean(field string) AggregateFunc {
	return func(s *sql.Selector) string {
		if err := checkColumn(s.TableName(), field); err != nil {
			s.AddError(&ValidationError{Name: field, err: fmt.Errorf("ent: %w", err)})
			return ""
		}
		return sql.Avg(s.C(field))
	}
}

// Min applies the "min" aggregation function on the given field of each group.
func Min(field string) AggregateFunc {
	return func(s *sql.Selector) string {
		if err := checkColumn(s.TableName(), field); err != nil {
			s.AddError(&ValidationError{Name: field, err: fmt.Errorf("ent: %w", err)})
			return ""
		}
		return sql.Min(s.C(field))
	}
}

// Sum applies the "sum" aggregation function on the given field of each group.
func Sum(field string) AggregateFunc {
	return func(s *sql.Selector) string {
		if err := checkColumn(s.TableName(), field); err != nil {
			s.AddError(&ValidationError{Name: field, err: fmt.Errorf("ent: %w", err)})
			return ""
		}
		return sql.Sum(s.C(field))
	}
}

// ValidationError returns when validating a field or edge fails.
type ValidationError struct {
	Name string // Field or edge name.
	err  error
}

// Error implements the error interface.
func (e *ValidationError) Error() string {
	return e.err.Error()
}

// Unwrap implements the errors.Wrapper interface.
func (e *ValidationError) Unwrap() error {
	return e.err
}

// IsValidationError returns a boolean indicating whether the error is a validation error.
func IsValidationError(err error) bool {
	if err == nil {
		return false
	}
	var e *ValidationError
	return errors.As(err, &e)
}

// NotFoundError returns when trying to fetch a specific entity and it was not found in the database.
type NotFoundError struct {
	label string
}

// Error implements the error interface.
func (e *NotFoundError) Error() string {
	return "ent: " + e.label + " not found"
}

// IsNotFound returns a boolean indicating whether the error is a not found error.
func IsNotFound(err error) bool {
	if err == nil {
		return false
	}
	var e *NotFoundError
	return errors.As(err, &e)
}

// MaskNotFound masks not found error.
func MaskNotFound(err error) error {
	if IsNotFound(err) {
		return nil
	}
	return err
}

// NotSingularError returns when trying to fetch a singular entity and more then one was found in the database.
type NotSingularError struct {
	label string
}

// Error implements the error interface.
func (e *NotSingularError) Error() string {
	return "ent: " + e.label + " not singular"
}

// IsNotSingular returns a boolean indicating whether the error is a not singular error.
func IsNotSingular(err error) bool {
	if err == nil {
		return false
	}
	var e *NotSingularError
	return errors.As(err, &e)
}

// NotLoadedError returns when trying to get a node that was not loaded by the query.
type NotLoadedError struct {
	edge string
}

// Error implements the error interface.
func (e *NotLoadedError) Error() string {
	return "ent: " + e.edge + " edge was not loaded"
}

// IsNotLoaded returns a boolean indicating whether the error is a not loaded error.
func IsNotLoaded(err error) bool {
	if err == nil {
		return false
	}
	var e *NotLoadedError
	return errors.As(err, &e)
}

// ConstraintError returns when trying to create/update one or more entities and
// one or more of their constraints failed. For example, violation of edge or
// field uniqueness.
type ConstraintError struct {
	msg  string
	wrap error
}

// Error implements the error interface.
func (e ConstraintError) Error() string {
	return "ent: constraint failed: " + e.msg
}

// Unwrap implements the errors.Wrapper interface.
func (e *ConstraintError) Unwrap() error {
	return e.wrap
}

// IsConstraintError returns a boolean indicating whether the error is a constraint failure.
func IsConstraintError(err error) bool {
	if err == nil {
		return false
	}
	var e *ConstraintError
	return errors.As(err, &e)
}

// selector embedded by the different Select/GroupBy builders.
type selector struct {
	label string
	flds  *[]string
	fns   []AggregateFunc
	scan  func(context.Context, any) error
}

// ScanX is like Scan, but panics if an error occurs.
func (s *selector) ScanX(ctx context.Context, v any) {
	if err := s.scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (s *selector) Strings(ctx context.Context) ([]string, error) {
	if len(*s.flds) > 1 {
		return nil, errors.New("ent: Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := s.scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (s *selector) StringsX(ctx context.Context) []string {
	v, err := s.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (s *selector) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = s.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{s.label}
	default:
		err = fmt.Errorf("ent: Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (s *selector) StringX(ctx context.Context) string {
	v, err := s.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (s *selector) Ints(ctx context.Context) ([]int, error) {
	if len(*s.flds) > 1 {
		return nil, errors.New("ent: Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := s.scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (s *selector) IntsX(ctx context.Context) []int {
	v, err := s.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (s *selector) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = s.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{s.label}
	default:
		err = fmt.Errorf("ent: Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (s *selector) IntX(ctx context.Context) int {
	v, err := s.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (s *selector) Float64s(ctx context.Context) ([]float64, error) {
	if len(*s.flds) > 1 {
		return nil, errors.New("ent: Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := s.scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (s *selector) Float64sX(ctx context.Context) []float64 {
	v, err := s.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (s *selector) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = s.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{s.label}
	default:
		err = fmt.Errorf("ent: Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (s *selector) Float64X(ctx context.Context) float64 {
	v, err := s.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (s *selector) Bools(ctx context.Context) ([]bool, error) {
	if len(*s.flds) > 1 {
		return nil, errors.New("ent: Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := s.scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (s *selector) BoolsX(ctx context.Context) []bool {
	v, err := s.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (s *selector) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = s.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{s.label}
	default:
		err = fmt.Errorf("ent: Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (s *selector) BoolX(ctx context.Context) bool {
	v, err := s.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// withHooks invokes the builder operation with the given hooks, if any.
func withHooks[V Value, M any, PM interface {
	*M
	Mutation
}](ctx context.Context, exec func(context.Context) (V, error), mutation PM, hooks []Hook) (value V, err error) {
	if len(hooks) == 0 {
		return exec(ctx)
	}
	var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
		mutationT, ok := any(m).(PM)
		if !ok {
			return nil, fmt.Errorf("unexpected mutation type %T", m)
		}
		// Set the mutation to the builder.
		*mutation = *mutationT
		return exec(ctx)
	})
	for i := len(hooks) - 1; i >= 0; i-- {
		if hooks[i] == nil {
			return value, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
		}
		mut = hooks[i](mut)
	}
	v, err := mut.Mutate(ctx, mutation)
	if err != nil {
		return value, err
	}
	nv, ok := v.(V)
	if !ok {
		return value, fmt.Errorf("unexpected node type %T returned from %T", v, mutation)
	}
	return nv, nil
}

// setContextOp returns a new context with the given QueryContext attached (including its op) in case it does not exist.
func setContextOp(ctx context.Context, qc *QueryContext, op string) context.Context {
	if ent.QueryFromContext(ctx) == nil {
		qc.Op = op
		ctx = ent.NewQueryContext(ctx, qc)
	}
	return ctx
}

func querierAll[V Value, Q interface {
	sqlAll(context.Context, ...queryHook) (V, error)
}]() Querier {
	return QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		query, ok := q.(Q)
		if !ok {
			return nil, fmt.Errorf("unexpected query type %T", q)
		}
		return query.sqlAll(ctx)
	})
}

func querierCount[Q interface {
	sqlCount(context.Context) (int, error)
}]() Querier {
	return QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		query, ok := q.(Q)
		if !ok {
			return nil, fmt.Errorf("unexpected query type %T", q)
		}
		return query.sqlCount(ctx)
	})
}

func withInterceptors[V Value](ctx context.Context, q Query, qr Querier, inters []Interceptor) (v V, err error) {
	for i := len(inters) - 1; i >= 0; i-- {
		qr = inters[i].Intercept(qr)
	}
	rv, err := qr.Query(ctx, q)
	if err != nil {
		return v, err
	}
	vt, ok := rv.(V)
	if !ok {
		return v, fmt.Errorf("unexpected type %T returned from %T. expected type: %T", vt, q, v)
	}
	return vt, nil
}

func scanWithInterceptors[Q1 ent.Query, Q2 interface {
	sqlScan(context.Context, Q1, any) error
}](ctx context.Context, rootQuery Q1, selectOrGroup Q2, inters []Interceptor, v any) error {
	rv := reflect.ValueOf(v)
	var qr Querier = QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		query, ok := q.(Q1)
		if !ok {
			return nil, fmt.Errorf("unexpected query type %T", q)
		}
		if err := selectOrGroup.sqlScan(ctx, query, v); err != nil {
			return nil, err
		}
		if k := rv.Kind(); k == reflect.Pointer && rv.Elem().CanInterface() {
			return rv.Elem().Interface(), nil
		}
		return v, nil
	})
	for i := len(inters) - 1; i >= 0; i-- {
		qr = inters[i].Intercept(qr)
	}
	vv, err := qr.Query(ctx, rootQuery)
	if err != nil {
		return err
	}
	switch rv2 := reflect.ValueOf(vv); {
	case rv.IsNil(), rv2.IsNil(), rv.Kind() != reflect.Pointer:
	case rv.Type() == rv2.Type():
		rv.Elem().Set(rv2.Elem())
	case rv.Elem().Type() == rv2.Type():
		rv.Elem().Set(rv2)
	}
	return nil
}

// queryHook describes an internal hook for the different sqlAll methods.
type queryHook func(context.Context, *sqlgraph.QuerySpec)
