// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/bengobox/pos-service/internal/ent/promotionredemption"
	"github.com/google/uuid"
)

// PromotionRedemptionUpdate is the builder for updating PromotionRedemption entities.
type PromotionRedemptionUpdate struct {
	config
	hooks    []Hook
	mutation *PromotionRedemptionMutation
}

// Where appends a list predicates to the PromotionRedemptionUpdate builder.
func (_u *PromotionRedemptionUpdate) Where(ps ...predicate.PromotionRedemption) *PromotionRedemptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *PromotionRedemptionUpdate) SetTenantID(v uuid.UUID) *PromotionRedemptionUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *PromotionRedemptionUpdate) SetNillableTenantID(v *uuid.UUID) *PromotionRedemptionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetPromotionID sets the "promotion_id" field.
func (_u *PromotionRedemptionUpdate) SetPromotionID(v uuid.UUID) *PromotionRedemptionUpdate {
	_u.mutation.SetPromotionID(v)
	return _u
}

// SetNillablePromotionID sets the "promotion_id" field if the given value is not nil.
func (_u *PromotionRedemptionUpdate) SetNillablePromotionID(v *uuid.UUID) *PromotionRedemptionUpdate {
	if v != nil {
		_u.SetPromotionID(*v)
	}
	return _u
}

// SetCustomerKey sets the "customer_key" field.
func (_u *PromotionRedemptionUpdate) SetCustomerKey(v string) *PromotionRedemptionUpdate {
	_u.mutation.SetCustomerKey(v)
	return _u
}

// SetNillableCustomerKey sets the "customer_key" field if the given value is not nil.
func (_u *PromotionRedemptionUpdate) SetNillableCustomerKey(v *string) *PromotionRedemptionUpdate {
	if v != nil {
		_u.SetCustomerKey(*v)
	}
	return _u
}

// ClearCustomerKey clears the value of the "customer_key" field.
func (_u *PromotionRedemptionUpdate) ClearCustomerKey() *PromotionRedemptionUpdate {
	_u.mutation.ClearCustomerKey()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PromotionRedemptionUpdate) SetChannel(v promotionredemption.Channel) *PromotionRedemptionUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PromotionRedemptionUpdate) SetNillableChannel(v *promotionredemption.Channel) *PromotionRedemptionUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *PromotionRedemptionUpdate) SetOrderID(v string) *PromotionRedemptionUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *PromotionRedemptionUpdate) SetNillableOrderID(v *string) *PromotionRedemptionUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *PromotionRedemptionUpdate) SetQuantity(v float64) *PromotionRedemptionUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *PromotionRedemptionUpdate) SetNillableQuantity(v *float64) *PromotionRedemptionUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *PromotionRedemptionUpdate) AddQuantity(v float64) *PromotionRedemptionUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// Mutation returns the PromotionRedemptionMutation object of the builder.
func (_u *PromotionRedemptionUpdate) Mutation() *PromotionRedemptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromotionRedemptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionRedemptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromotionRedemptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionRedemptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromotionRedemptionUpdate) check() error {
	if v, ok := _u.mutation.Channel(); ok {
		if err := promotionredemption.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "PromotionRedemption.channel": %w`, err)}
		}
	}
	return nil
}

func (_u *PromotionRedemptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promotionredemption.Table, promotionredemption.Columns, sqlgraph.NewFieldSpec(promotionredemption.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(promotionredemption.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PromotionID(); ok {
		_spec.SetField(promotionredemption.FieldPromotionID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CustomerKey(); ok {
		_spec.SetField(promotionredemption.FieldCustomerKey, field.TypeString, value)
	}
	if _u.mutation.CustomerKeyCleared() {
		_spec.ClearField(promotionredemption.FieldCustomerKey, field.TypeString)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(promotionredemption.FieldChannel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(promotionredemption.FieldOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(promotionredemption.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(promotionredemption.FieldQuantity, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotionredemption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromotionRedemptionUpdateOne is the builder for updating a single PromotionRedemption entity.
type PromotionRedemptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromotionRedemptionMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *PromotionRedemptionUpdateOne) SetTenantID(v uuid.UUID) *PromotionRedemptionUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *PromotionRedemptionUpdateOne) SetNillableTenantID(v *uuid.UUID) *PromotionRedemptionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetPromotionID sets the "promotion_id" field.
func (_u *PromotionRedemptionUpdateOne) SetPromotionID(v uuid.UUID) *PromotionRedemptionUpdateOne {
	_u.mutation.SetPromotionID(v)
	return _u
}

// SetNillablePromotionID sets the "promotion_id" field if the given value is not nil.
func (_u *PromotionRedemptionUpdateOne) SetNillablePromotionID(v *uuid.UUID) *PromotionRedemptionUpdateOne {
	if v != nil {
		_u.SetPromotionID(*v)
	}
	return _u
}

// SetCustomerKey sets the "customer_key" field.
func (_u *PromotionRedemptionUpdateOne) SetCustomerKey(v string) *PromotionRedemptionUpdateOne {
	_u.mutation.SetCustomerKey(v)
	return _u
}

// SetNillableCustomerKey sets the "customer_key" field if the given value is not nil.
func (_u *PromotionRedemptionUpdateOne) SetNillableCustomerKey(v *string) *PromotionRedemptionUpdateOne {
	if v != nil {
		_u.SetCustomerKey(*v)
	}
	return _u
}

// ClearCustomerKey clears the value of the "customer_key" field.
func (_u *PromotionRedemptionUpdateOne) ClearCustomerKey() *PromotionRedemptionUpdateOne {
	_u.mutation.ClearCustomerKey()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *PromotionRedemptionUpdateOne) SetChannel(v promotionredemption.Channel) *PromotionRedemptionUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *PromotionRedemptionUpdateOne) SetNillableChannel(v *promotionredemption.Channel) *PromotionRedemptionUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *PromotionRedemptionUpdateOne) SetOrderID(v string) *PromotionRedemptionUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *PromotionRedemptionUpdateOne) SetNillableOrderID(v *string) *PromotionRedemptionUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *PromotionRedemptionUpdateOne) SetQuantity(v float64) *PromotionRedemptionUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *PromotionRedemptionUpdateOne) SetNillableQuantity(v *float64) *PromotionRedemptionUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *PromotionRedemptionUpdateOne) AddQuantity(v float64) *PromotionRedemptionUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// Mutation returns the PromotionRedemptionMutation object of the builder.
func (_u *PromotionRedemptionUpdateOne) Mutation() *PromotionRedemptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the PromotionRedemptionUpdate builder.
func (_u *PromotionRedemptionUpdateOne) Where(ps ...predicate.PromotionRedemption) *PromotionRedemptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromotionRedemptionUpdateOne) Select(field string, fields ...string) *PromotionRedemptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromotionRedemption entity.
func (_u *PromotionRedemptionUpdateOne) Save(ctx context.Context) (*PromotionRedemption, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionRedemptionUpdateOne) SaveX(ctx context.Context) *PromotionRedemption {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromotionRedemptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionRedemptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromotionRedemptionUpdateOne) check() error {
	if v, ok := _u.mutation.Channel(); ok {
		if err := promotionredemption.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "PromotionRedemption.channel": %w`, err)}
		}
	}
	return nil
}

func (_u *PromotionRedemptionUpdateOne) sqlSave(ctx context.Context) (_node *PromotionRedemption, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promotionredemption.Table, promotionredemption.Columns, sqlgraph.NewFieldSpec(promotionredemption.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromotionRedemption.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promotionredemption.FieldID)
		for _, f := range fields {
			if !promotionredemption.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promotionredemption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(promotionredemption.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PromotionID(); ok {
		_spec.SetField(promotionredemption.FieldPromotionID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CustomerKey(); ok {
		_spec.SetField(promotionredemption.FieldCustomerKey, field.TypeString, value)
	}
	if _u.mutation.CustomerKeyCleared() {
		_spec.ClearField(promotionredemption.FieldCustomerKey, field.TypeString)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(promotionredemption.FieldChannel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(promotionredemption.FieldOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(promotionredemption.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(promotionredemption.FieldQuantity, field.TypeFloat64, value)
	}
	_node = &PromotionRedemption{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotionredemption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
