// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/promotion"
	"github.com/google/uuid"
)

// Promotion is the model entity for the Promotion schema.
type Promotion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Outlet scope; nil = applies to all outlets for this tenant
	OutletID *uuid.UUID `json:"outlet_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PromoCode holds the value of the "promo_code" field.
	PromoCode *string `json:"promo_code,omitempty"`
	// code = manual promo code; happy_hour = time-windowed auto discount; auto = always-on auto discount
	PromoKind promotion.PromoKind `json:"promo_kind,omitempty"`
	// Days the promo is active (0=Sun..6=Sat); empty = all days. Used by happy_hour
	DaysOfWeek []int `json:"days_of_week,omitempty"`
	// Daily activation start time HH:MM (happy_hour)
	WindowStart string `json:"window_start,omitempty"`
	// Daily activation end time HH:MM (happy_hour)
	WindowEnd string `json:"window_end,omitempty"`
	// Apply automatically at checkout without a code (happy_hour/auto)
	AutoApply bool `json:"auto_apply,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StartAt holds the value of the "start_at" field.
	StartAt time.Time `json:"start_at,omitempty"`
	// EndAt holds the value of the "end_at" field.
	EndAt *time.Time `json:"end_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Total redemption cap across all channels combined; nil/0 = unlimited
	UsageLimit *int `json:"usage_limit,omitempty"`
	// Per-customer redemption cap, matched by phone/customer key; nil/0 = unlimited
	MaxUnitsPerCustomer *int `json:"max_units_per_customer,omitempty"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Promotion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promotion.FieldOutletID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case promotion.FieldDaysOfWeek, promotion.FieldMetadata:
			values[i] = new([]byte)
		case promotion.FieldAutoApply:
			values[i] = new(sql.NullBool)
		case promotion.FieldUsageLimit, promotion.FieldMaxUnitsPerCustomer:
			values[i] = new(sql.NullInt64)
		case promotion.FieldName, promotion.FieldDescription, promotion.FieldPromoCode, promotion.FieldPromoKind, promotion.FieldWindowStart, promotion.FieldWindowEnd, promotion.FieldStatus:
			values[i] = new(sql.NullString)
		case promotion.FieldStartAt, promotion.FieldEndAt:
			values[i] = new(sql.NullTime)
		case promotion.FieldID, promotion.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Promotion fields.
func (_m *Promotion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promotion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case promotion.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case promotion.FieldOutletID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field outlet_id", values[i])
			} else if value.Valid {
				_m.OutletID = new(uuid.UUID)
				*_m.OutletID = *value.S.(*uuid.UUID)
			}
		case promotion.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case promotion.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case promotion.FieldPromoCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field promo_code", values[i])
			} else if value.Valid {
				_m.PromoCode = new(string)
				*_m.PromoCode = value.String
			}
		case promotion.FieldPromoKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field promo_kind", values[i])
			} else if value.Valid {
				_m.PromoKind = promotion.PromoKind(value.String)
			}
		case promotion.FieldDaysOfWeek:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field days_of_week", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DaysOfWeek); err != nil {
					return fmt.Errorf("unmarshal field days_of_week: %w", err)
				}
			}
		case promotion.FieldWindowStart:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field window_start", values[i])
			} else if value.Valid {
				_m.WindowStart = value.String
			}
		case promotion.FieldWindowEnd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field window_end", values[i])
			} else if value.Valid {
				_m.WindowEnd = value.String
			}
		case promotion.FieldAutoApply:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_apply", values[i])
			} else if value.Valid {
				_m.AutoApply = value.Bool
			}
		case promotion.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case promotion.FieldStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_at", values[i])
			} else if value.Valid {
				_m.StartAt = value.Time
			}
		case promotion.FieldEndAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_at", values[i])
			} else if value.Valid {
				_m.EndAt = new(time.Time)
				*_m.EndAt = value.Time
			}
		case promotion.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case promotion.FieldUsageLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_limit", values[i])
			} else if value.Valid {
				_m.UsageLimit = new(int)
				*_m.UsageLimit = int(value.Int64)
			}
		case promotion.FieldMaxUnitsPerCustomer:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_units_per_customer", values[i])
			} else if value.Valid {
				_m.MaxUnitsPerCustomer = new(int)
				*_m.MaxUnitsPerCustomer = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Promotion.
// This includes values selected through modifiers, order, etc.
func (_m *Promotion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Promotion.
// Note that you need to call Promotion.Unwrap() before calling this method if this Promotion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Promotion) Update() *PromotionUpdateOne {
	return NewPromotionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Promotion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Promotion) Unwrap() *Promotion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Promotion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Promotion) String() string {
	var builder strings.Builder
	builder.WriteString("Promotion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	if v := _m.OutletID; v != nil {
		builder.WriteString("outlet_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	if v := _m.PromoCode; v != nil {
		builder.WriteString("promo_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("promo_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromoKind))
	builder.WriteString(", ")
	builder.WriteString("days_of_week=")
	builder.WriteString(fmt.Sprintf("%v", _m.DaysOfWeek))
	builder.WriteString(", ")
	builder.WriteString("window_start=")
	builder.WriteString(_m.WindowStart)
	builder.WriteString(", ")
	builder.WriteString("window_end=")
	builder.WriteString(_m.WindowEnd)
	builder.WriteString(", ")
	builder.WriteString("auto_apply=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoApply))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("start_at=")
	builder.WriteString(_m.StartAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndAt; v != nil {
		builder.WriteString("end_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.UsageLimit; v != nil {
		builder.WriteString("usage_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxUnitsPerCustomer; v != nil {
		builder.WriteString("max_units_per_customer=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Promotions is a parsable slice of Promotion.
type Promotions []*Promotion
