// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/bengobox/pos-service/internal/ent/promotion"
	"github.com/google/uuid"
)

// PromotionUpdate is the builder for updating Promotion entities.
type PromotionUpdate struct {
	config
	hooks    []Hook
	mutation *PromotionMutation
}

// Where appends a list predicates to the PromotionUpdate builder.
func (_u *PromotionUpdate) Where(ps ...predicate.Promotion) *PromotionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *PromotionUpdate) SetTenantID(v uuid.UUID) *PromotionUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableTenantID(v *uuid.UUID) *PromotionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *PromotionUpdate) SetOutletID(v uuid.UUID) *PromotionUpdate {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableOutletID(v *uuid.UUID) *PromotionUpdate {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// ClearOutletID clears the value of the "outlet_id" field.
func (_u *PromotionUpdate) ClearOutletID() *PromotionUpdate {
	_u.mutation.ClearOutletID()
	return _u
}

// SetName sets the "name" field.
func (_u *PromotionUpdate) SetName(v string) *PromotionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableName(v *string) *PromotionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PromotionUpdate) SetDescription(v string) *PromotionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableDescription(v *string) *PromotionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PromotionUpdate) ClearDescription() *PromotionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPromoCode sets the "promo_code" field.
func (_u *PromotionUpdate) SetPromoCode(v string) *PromotionUpdate {
	_u.mutation.SetPromoCode(v)
	return _u
}

// SetNillablePromoCode sets the "promo_code" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillablePromoCode(v *string) *PromotionUpdate {
	if v != nil {
		_u.SetPromoCode(*v)
	}
	return _u
}

// ClearPromoCode clears the value of the "promo_code" field.
func (_u *PromotionUpdate) ClearPromoCode() *PromotionUpdate {
	_u.mutation.ClearPromoCode()
	return _u
}

// SetPromoKind sets the "promo_kind" field.
func (_u *PromotionUpdate) SetPromoKind(v promotion.PromoKind) *PromotionUpdate {
	_u.mutation.SetPromoKind(v)
	return _u
}

// SetNillablePromoKind sets the "promo_kind" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillablePromoKind(v *promotion.PromoKind) *PromotionUpdate {
	if v != nil {
		_u.SetPromoKind(*v)
	}
	return _u
}

// SetDaysOfWeek sets the "days_of_week" field.
func (_u *PromotionUpdate) SetDaysOfWeek(v []int) *PromotionUpdate {
	_u.mutation.SetDaysOfWeek(v)
	return _u
}

// AppendDaysOfWeek appends value to the "days_of_week" field.
func (_u *PromotionUpdate) AppendDaysOfWeek(v []int) *PromotionUpdate {
	_u.mutation.AppendDaysOfWeek(v)
	return _u
}

// ClearDaysOfWeek clears the value of the "days_of_week" field.
func (_u *PromotionUpdate) ClearDaysOfWeek() *PromotionUpdate {
	_u.mutation.ClearDaysOfWeek()
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *PromotionUpdate) SetWindowStart(v string) *PromotionUpdate {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableWindowStart(v *string) *PromotionUpdate {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// ClearWindowStart clears the value of the "window_start" field.
func (_u *PromotionUpdate) ClearWindowStart() *PromotionUpdate {
	_u.mutation.ClearWindowStart()
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *PromotionUpdate) SetWindowEnd(v string) *PromotionUpdate {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableWindowEnd(v *string) *PromotionUpdate {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// ClearWindowEnd clears the value of the "window_end" field.
func (_u *PromotionUpdate) ClearWindowEnd() *PromotionUpdate {
	_u.mutation.ClearWindowEnd()
	return _u
}

// SetAutoApply sets the "auto_apply" field.
func (_u *PromotionUpdate) SetAutoApply(v bool) *PromotionUpdate {
	_u.mutation.SetAutoApply(v)
	return _u
}

// SetNillableAutoApply sets the "auto_apply" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableAutoApply(v *bool) *PromotionUpdate {
	if v != nil {
		_u.SetAutoApply(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PromotionUpdate) SetStatus(v string) *PromotionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableStatus(v *string) *PromotionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *PromotionUpdate) SetStartAt(v time.Time) *PromotionUpdate {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableStartAt(v *time.Time) *PromotionUpdate {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// SetEndAt sets the "end_at" field.
func (_u *PromotionUpdate) SetEndAt(v time.Time) *PromotionUpdate {
	_u.mutation.SetEndAt(v)
	return _u
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableEndAt(v *time.Time) *PromotionUpdate {
	if v != nil {
		_u.SetEndAt(*v)
	}
	return _u
}

// ClearEndAt clears the value of the "end_at" field.
func (_u *PromotionUpdate) ClearEndAt() *PromotionUpdate {
	_u.mutation.ClearEndAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PromotionUpdate) SetMetadata(v map[string]interface{}) *PromotionUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUsageLimit sets the "usage_limit" field.
func (_u *PromotionUpdate) SetUsageLimit(v int) *PromotionUpdate {
	_u.mutation.ResetUsageLimit()
	_u.mutation.SetUsageLimit(v)
	return _u
}

// SetNillableUsageLimit sets the "usage_limit" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableUsageLimit(v *int) *PromotionUpdate {
	if v != nil {
		_u.SetUsageLimit(*v)
	}
	return _u
}

// AddUsageLimit adds value to the "usage_limit" field.
func (_u *PromotionUpdate) AddUsageLimit(v int) *PromotionUpdate {
	_u.mutation.AddUsageLimit(v)
	return _u
}

// ClearUsageLimit clears the value of the "usage_limit" field.
func (_u *PromotionUpdate) ClearUsageLimit() *PromotionUpdate {
	_u.mutation.ClearUsageLimit()
	return _u
}

// SetMaxUnitsPerCustomer sets the "max_units_per_customer" field.
func (_u *PromotionUpdate) SetMaxUnitsPerCustomer(v int) *PromotionUpdate {
	_u.mutation.ResetMaxUnitsPerCustomer()
	_u.mutation.SetMaxUnitsPerCustomer(v)
	return _u
}

// SetNillableMaxUnitsPerCustomer sets the "max_units_per_customer" field if the given value is not nil.
func (_u *PromotionUpdate) SetNillableMaxUnitsPerCustomer(v *int) *PromotionUpdate {
	if v != nil {
		_u.SetMaxUnitsPerCustomer(*v)
	}
	return _u
}

// AddMaxUnitsPerCustomer adds value to the "max_units_per_customer" field.
func (_u *PromotionUpdate) AddMaxUnitsPerCustomer(v int) *PromotionUpdate {
	_u.mutation.AddMaxUnitsPerCustomer(v)
	return _u
}

// ClearMaxUnitsPerCustomer clears the value of the "max_units_per_customer" field.
func (_u *PromotionUpdate) ClearMaxUnitsPerCustomer() *PromotionUpdate {
	_u.mutation.ClearMaxUnitsPerCustomer()
	return _u
}

// Mutation returns the PromotionMutation object of the builder.
func (_u *PromotionUpdate) Mutation() *PromotionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromotionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromotionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromotionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := promotion.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Promotion.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromoKind(); ok {
		if err := promotion.PromoKindValidator(v); err != nil {
			return &ValidationError{Name: "promo_kind", err: fmt.Errorf(`ent: validator failed for field "Promotion.promo_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *PromotionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promotion.Table, promotion.Columns, sqlgraph.NewFieldSpec(promotion.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(promotion.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(promotion.FieldOutletID, field.TypeUUID, value)
	}
	if _u.mutation.OutletIDCleared() {
		_spec.ClearField(promotion.FieldOutletID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(promotion.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(promotion.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(promotion.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PromoCode(); ok {
		_spec.SetField(promotion.FieldPromoCode, field.TypeString, value)
	}
	if _u.mutation.PromoCodeCleared() {
		_spec.ClearField(promotion.FieldPromoCode, field.TypeString)
	}
	if value, ok := _u.mutation.PromoKind(); ok {
		_spec.SetField(promotion.FieldPromoKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DaysOfWeek(); ok {
		_spec.SetField(promotion.FieldDaysOfWeek, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDaysOfWeek(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, promotion.FieldDaysOfWeek, value)
		})
	}
	if _u.mutation.DaysOfWeekCleared() {
		_spec.ClearField(promotion.FieldDaysOfWeek, field.TypeJSON)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(promotion.FieldWindowStart, field.TypeString, value)
	}
	if _u.mutation.WindowStartCleared() {
		_spec.ClearField(promotion.FieldWindowStart, field.TypeString)
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(promotion.FieldWindowEnd, field.TypeString, value)
	}
	if _u.mutation.WindowEndCleared() {
		_spec.ClearField(promotion.FieldWindowEnd, field.TypeString)
	}
	if value, ok := _u.mutation.AutoApply(); ok {
		_spec.SetField(promotion.FieldAutoApply, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(promotion.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(promotion.FieldStartAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndAt(); ok {
		_spec.SetField(promotion.FieldEndAt, field.TypeTime, value)
	}
	if _u.mutation.EndAtCleared() {
		_spec.ClearField(promotion.FieldEndAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(promotion.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UsageLimit(); ok {
		_spec.SetField(promotion.FieldUsageLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsageLimit(); ok {
		_spec.AddField(promotion.FieldUsageLimit, field.TypeInt, value)
	}
	if _u.mutation.UsageLimitCleared() {
		_spec.ClearField(promotion.FieldUsageLimit, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxUnitsPerCustomer(); ok {
		_spec.SetField(promotion.FieldMaxUnitsPerCustomer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUnitsPerCustomer(); ok {
		_spec.AddField(promotion.FieldMaxUnitsPerCustomer, field.TypeInt, value)
	}
	if _u.mutation.MaxUnitsPerCustomerCleared() {
		_spec.ClearField(promotion.FieldMaxUnitsPerCustomer, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromotionUpdateOne is the builder for updating a single Promotion entity.
type PromotionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromotionMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *PromotionUpdateOne) SetTenantID(v uuid.UUID) *PromotionUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableTenantID(v *uuid.UUID) *PromotionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *PromotionUpdateOne) SetOutletID(v uuid.UUID) *PromotionUpdateOne {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableOutletID(v *uuid.UUID) *PromotionUpdateOne {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// ClearOutletID clears the value of the "outlet_id" field.
func (_u *PromotionUpdateOne) ClearOutletID() *PromotionUpdateOne {
	_u.mutation.ClearOutletID()
	return _u
}

// SetName sets the "name" field.
func (_u *PromotionUpdateOne) SetName(v string) *PromotionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableName(v *string) *PromotionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PromotionUpdateOne) SetDescription(v string) *PromotionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableDescription(v *string) *PromotionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PromotionUpdateOne) ClearDescription() *PromotionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPromoCode sets the "promo_code" field.
func (_u *PromotionUpdateOne) SetPromoCode(v string) *PromotionUpdateOne {
	_u.mutation.SetPromoCode(v)
	return _u
}

// SetNillablePromoCode sets the "promo_code" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillablePromoCode(v *string) *PromotionUpdateOne {
	if v != nil {
		_u.SetPromoCode(*v)
	}
	return _u
}

// ClearPromoCode clears the value of the "promo_code" field.
func (_u *PromotionUpdateOne) ClearPromoCode() *PromotionUpdateOne {
	_u.mutation.ClearPromoCode()
	return _u
}

// SetPromoKind sets the "promo_kind" field.
func (_u *PromotionUpdateOne) SetPromoKind(v promotion.PromoKind) *PromotionUpdateOne {
	_u.mutation.SetPromoKind(v)
	return _u
}

// SetNillablePromoKind sets the "promo_kind" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillablePromoKind(v *promotion.PromoKind) *PromotionUpdateOne {
	if v != nil {
		_u.SetPromoKind(*v)
	}
	return _u
}

// SetDaysOfWeek sets the "days_of_week" field.
func (_u *PromotionUpdateOne) SetDaysOfWeek(v []int) *PromotionUpdateOne {
	_u.mutation.SetDaysOfWeek(v)
	return _u
}

// AppendDaysOfWeek appends value to the "days_of_week" field.
func (_u *PromotionUpdateOne) AppendDaysOfWeek(v []int) *PromotionUpdateOne {
	_u.mutation.AppendDaysOfWeek(v)
	return _u
}

// ClearDaysOfWeek clears the value of the "days_of_week" field.
func (_u *PromotionUpdateOne) ClearDaysOfWeek() *PromotionUpdateOne {
	_u.mutation.ClearDaysOfWeek()
	return _u
}

// SetWindowStart sets the "window_start" field.
func (_u *PromotionUpdateOne) SetWindowStart(v string) *PromotionUpdateOne {
	_u.mutation.SetWindowStart(v)
	return _u
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableWindowStart(v *string) *PromotionUpdateOne {
	if v != nil {
		_u.SetWindowStart(*v)
	}
	return _u
}

// ClearWindowStart clears the value of the "window_start" field.
func (_u *PromotionUpdateOne) ClearWindowStart() *PromotionUpdateOne {
	_u.mutation.ClearWindowStart()
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *PromotionUpdateOne) SetWindowEnd(v string) *PromotionUpdateOne {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableWindowEnd(v *string) *PromotionUpdateOne {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// ClearWindowEnd clears the value of the "window_end" field.
func (_u *PromotionUpdateOne) ClearWindowEnd() *PromotionUpdateOne {
	_u.mutation.ClearWindowEnd()
	return _u
}

// SetAutoApply sets the "auto_apply" field.
func (_u *PromotionUpdateOne) SetAutoApply(v bool) *PromotionUpdateOne {
	_u.mutation.SetAutoApply(v)
	return _u
}

// SetNillableAutoApply sets the "auto_apply" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableAutoApply(v *bool) *PromotionUpdateOne {
	if v != nil {
		_u.SetAutoApply(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PromotionUpdateOne) SetStatus(v string) *PromotionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableStatus(v *string) *PromotionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *PromotionUpdateOne) SetStartAt(v time.Time) *PromotionUpdateOne {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableStartAt(v *time.Time) *PromotionUpdateOne {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// SetEndAt sets the "end_at" field.
func (_u *PromotionUpdateOne) SetEndAt(v time.Time) *PromotionUpdateOne {
	_u.mutation.SetEndAt(v)
	return _u
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableEndAt(v *time.Time) *PromotionUpdateOne {
	if v != nil {
		_u.SetEndAt(*v)
	}
	return _u
}

// ClearEndAt clears the value of the "end_at" field.
func (_u *PromotionUpdateOne) ClearEndAt() *PromotionUpdateOne {
	_u.mutation.ClearEndAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PromotionUpdateOne) SetMetadata(v map[string]interface{}) *PromotionUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUsageLimit sets the "usage_limit" field.
func (_u *PromotionUpdateOne) SetUsageLimit(v int) *PromotionUpdateOne {
	_u.mutation.ResetUsageLimit()
	_u.mutation.SetUsageLimit(v)
	return _u
}

// SetNillableUsageLimit sets the "usage_limit" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableUsageLimit(v *int) *PromotionUpdateOne {
	if v != nil {
		_u.SetUsageLimit(*v)
	}
	return _u
}

// AddUsageLimit adds value to the "usage_limit" field.
func (_u *PromotionUpdateOne) AddUsageLimit(v int) *PromotionUpdateOne {
	_u.mutation.AddUsageLimit(v)
	return _u
}

// ClearUsageLimit clears the value of the "usage_limit" field.
func (_u *PromotionUpdateOne) ClearUsageLimit() *PromotionUpdateOne {
	_u.mutation.ClearUsageLimit()
	return _u
}

// SetMaxUnitsPerCustomer sets the "max_units_per_customer" field.
func (_u *PromotionUpdateOne) SetMaxUnitsPerCustomer(v int) *PromotionUpdateOne {
	_u.mutation.ResetMaxUnitsPerCustomer()
	_u.mutation.SetMaxUnitsPerCustomer(v)
	return _u
}

// SetNillableMaxUnitsPerCustomer sets the "max_units_per_customer" field if the given value is not nil.
func (_u *PromotionUpdateOne) SetNillableMaxUnitsPerCustomer(v *int) *PromotionUpdateOne {
	if v != nil {
		_u.SetMaxUnitsPerCustomer(*v)
	}
	return _u
}

// AddMaxUnitsPerCustomer adds value to the "max_units_per_customer" field.
func (_u *PromotionUpdateOne) AddMaxUnitsPerCustomer(v int) *PromotionUpdateOne {
	_u.mutation.AddMaxUnitsPerCustomer(v)
	return _u
}

// ClearMaxUnitsPerCustomer clears the value of the "max_units_per_customer" field.
func (_u *PromotionUpdateOne) ClearMaxUnitsPerCustomer() *PromotionUpdateOne {
	_u.mutation.ClearMaxUnitsPerCustomer()
	return _u
}

// Mutation returns the PromotionMutation object of the builder.
func (_u *PromotionUpdateOne) Mutation() *PromotionMutation {
	return _u.mutation
}

// Where appends a list predicates to the PromotionUpdate builder.
func (_u *PromotionUpdateOne) Where(ps ...predicate.Promotion) *PromotionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromotionUpdateOne) Select(field string, fields ...string) *PromotionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Promotion entity.
func (_u *PromotionUpdateOne) Save(ctx context.Context) (*Promotion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromotionUpdateOne) SaveX(ctx context.Context) *Promotion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromotionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromotionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromotionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := promotion.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Promotion.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromoKind(); ok {
		if err := promotion.PromoKindValidator(v); err != nil {
			return &ValidationError{Name: "promo_kind", err: fmt.Errorf(`ent: validator failed for field "Promotion.promo_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *PromotionUpdateOne) sqlSave(ctx context.Context) (_node *Promotion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promotion.Table, promotion.Columns, sqlgraph.NewFieldSpec(promotion.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Promotion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promotion.FieldID)
		for _, f := range fields {
			if !promotion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promotion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(promotion.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(promotion.FieldOutletID, field.TypeUUID, value)
	}
	if _u.mutation.OutletIDCleared() {
		_spec.ClearField(promotion.FieldOutletID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(promotion.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(promotion.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(promotion.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PromoCode(); ok {
		_spec.SetField(promotion.FieldPromoCode, field.TypeString, value)
	}
	if _u.mutation.PromoCodeCleared() {
		_spec.ClearField(promotion.FieldPromoCode, field.TypeString)
	}
	if value, ok := _u.mutation.PromoKind(); ok {
		_spec.SetField(promotion.FieldPromoKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DaysOfWeek(); ok {
		_spec.SetField(promotion.FieldDaysOfWeek, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDaysOfWeek(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, promotion.FieldDaysOfWeek, value)
		})
	}
	if _u.mutation.DaysOfWeekCleared() {
		_spec.ClearField(promotion.FieldDaysOfWeek, field.TypeJSON)
	}
	if value, ok := _u.mutation.WindowStart(); ok {
		_spec.SetField(promotion.FieldWindowStart, field.TypeString, value)
	}
	if _u.mutation.WindowStartCleared() {
		_spec.ClearField(promotion.FieldWindowStart, field.TypeString)
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(promotion.FieldWindowEnd, field.TypeString, value)
	}
	if _u.mutation.WindowEndCleared() {
		_spec.ClearField(promotion.FieldWindowEnd, field.TypeString)
	}
	if value, ok := _u.mutation.AutoApply(); ok {
		_spec.SetField(promotion.FieldAutoApply, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(promotion.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(promotion.FieldStartAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndAt(); ok {
		_spec.SetField(promotion.FieldEndAt, field.TypeTime, value)
	}
	if _u.mutation.EndAtCleared() {
		_spec.ClearField(promotion.FieldEndAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(promotion.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UsageLimit(); ok {
		_spec.SetField(promotion.FieldUsageLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsageLimit(); ok {
		_spec.AddField(promotion.FieldUsageLimit, field.TypeInt, value)
	}
	if _u.mutation.UsageLimitCleared() {
		_spec.ClearField(promotion.FieldUsageLimit, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxUnitsPerCustomer(); ok {
		_spec.SetField(promotion.FieldMaxUnitsPerCustomer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUnitsPerCustomer(); ok {
		_spec.AddField(promotion.FieldMaxUnitsPerCustomer, field.TypeInt, value)
	}
	if _u.mutation.MaxUnitsPerCustomerCleared() {
		_spec.ClearField(promotion.FieldMaxUnitsPerCustomer, field.TypeInt)
	}
	_node = &Promotion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promotion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
