// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/promotionredemption"
	"github.com/google/uuid"
)

// PromotionRedemptionCreate is the builder for creating a PromotionRedemption entity.
type PromotionRedemptionCreate struct {
	config
	mutation *PromotionRedemptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *PromotionRedemptionCreate) SetTenantID(v uuid.UUID) *PromotionRedemptionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetPromotionID sets the "promotion_id" field.
func (_c *PromotionRedemptionCreate) SetPromotionID(v uuid.UUID) *PromotionRedemptionCreate {
	_c.mutation.SetPromotionID(v)
	return _c
}

// SetCustomerKey sets the "customer_key" field.
func (_c *PromotionRedemptionCreate) SetCustomerKey(v string) *PromotionRedemptionCreate {
	_c.mutation.SetCustomerKey(v)
	return _c
}

// SetNillableCustomerKey sets the "customer_key" field if the given value is not nil.
func (_c *PromotionRedemptionCreate) SetNillableCustomerKey(v *string) *PromotionRedemptionCreate {
	if v != nil {
		_c.SetCustomerKey(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *PromotionRedemptionCreate) SetChannel(v promotionredemption.Channel) *PromotionRedemptionCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *PromotionRedemptionCreate) SetOrderID(v string) *PromotionRedemptionCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *PromotionRedemptionCreate) SetQuantity(v float64) *PromotionRedemptionCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromotionRedemptionCreate) SetCreatedAt(v time.Time) *PromotionRedemptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromotionRedemptionCreate) SetNillableCreatedAt(v *time.Time) *PromotionRedemptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromotionRedemptionCreate) SetID(v uuid.UUID) *PromotionRedemptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PromotionRedemptionCreate) SetNillableID(v *uuid.UUID) *PromotionRedemptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PromotionRedemptionMutation object of the builder.
func (_c *PromotionRedemptionCreate) Mutation() *PromotionRedemptionMutation {
	return _c.mutation
}

// Save creates the PromotionRedemption in the database.
func (_c *PromotionRedemptionCreate) Save(ctx context.Context) (*PromotionRedemption, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionRedemptionCreate) SaveX(ctx context.Context) *PromotionRedemption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionRedemptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionRedemptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionRedemptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promotionredemption.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := promotionredemption.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionRedemptionCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PromotionRedemption.tenant_id"`)}
	}
	if _, ok := _c.mutation.PromotionID(); !ok {
		return &ValidationError{Name: "promotion_id", err: errors.New(`ent: missing required field "PromotionRedemption.promotion_id"`)}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "PromotionRedemption.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := promotionredemption.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "PromotionRedemption.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "PromotionRedemption.order_id"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "PromotionRedemption.quantity"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromotionRedemption.created_at"`)}
	}
	return nil
}

func (_c *PromotionRedemptionCreate) sqlSave(ctx context.Context) (*PromotionRedemption, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionRedemptionCreate) createSpec() (*PromotionRedemption, *sqlgraph.CreateSpec) {
	var (
		_node = &PromotionRedemption{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotionredemption.Table, sqlgraph.NewFieldSpec(promotionredemption.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(promotionredemption.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.PromotionID(); ok {
		_spec.SetField(promotionredemption.FieldPromotionID, field.TypeUUID, value)
		_node.PromotionID = value
	}
	if value, ok := _c.mutation.CustomerKey(); ok {
		_spec.SetField(promotionredemption.FieldCustomerKey, field.TypeString, value)
		_node.CustomerKey = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(promotionredemption.FieldChannel, field.TypeEnum, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(promotionredemption.FieldOrderID, field.TypeString, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(promotionredemption.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promotionredemption.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionRedemption.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionRedemptionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionRedemptionCreate) OnConflict(opts ...sql.ConflictOption) *PromotionRedemptionUpsertOne {
	_c.conflict = opts
	return &PromotionRedemptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionRedemption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionRedemptionCreate) OnConflictColumns(columns ...string) *PromotionRedemptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionRedemptionUpsertOne{
		create: _c,
	}
}

type (
	// PromotionRedemptionUpsertOne is the builder for "upsert"-ing
	//  one PromotionRedemption node.
	PromotionRedemptionUpsertOne struct {
		create *PromotionRedemptionCreate
	}

	// PromotionRedemptionUpsert is the "OnConflict" setter.
	PromotionRedemptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *PromotionRedemptionUpsert) SetTenantID(v uuid.UUID) *PromotionRedemptionUpsert {
	u.Set(promotionredemption.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsert) UpdateTenantID() *PromotionRedemptionUpsert {
	u.SetExcluded(promotionredemption.FieldTenantID)
	return u
}

// SetPromotionID sets the "promotion_id" field.
func (u *PromotionRedemptionUpsert) SetPromotionID(v uuid.UUID) *PromotionRedemptionUpsert {
	u.Set(promotionredemption.FieldPromotionID, v)
	return u
}

// UpdatePromotionID sets the "promotion_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsert) UpdatePromotionID() *PromotionRedemptionUpsert {
	u.SetExcluded(promotionredemption.FieldPromotionID)
	return u
}

// SetCustomerKey sets the "customer_key" field.
func (u *PromotionRedemptionUpsert) SetCustomerKey(v string) *PromotionRedemptionUpsert {
	u.Set(promotionredemption.FieldCustomerKey, v)
	return u
}

// UpdateCustomerKey sets the "customer_key" field to the value that was provided on create.
func (u *PromotionRedemptionUpsert) UpdateCustomerKey() *PromotionRedemptionUpsert {
	u.SetExcluded(promotionredemption.FieldCustomerKey)
	return u
}

// ClearCustomerKey clears the value of the "customer_key" field.
func (u *PromotionRedemptionUpsert) ClearCustomerKey() *PromotionRedemptionUpsert {
	u.SetNull(promotionredemption.FieldCustomerKey)
	return u
}

// SetChannel sets the "channel" field.
func (u *PromotionRedemptionUpsert) SetChannel(v promotionredemption.Channel) *PromotionRedemptionUpsert {
	u.Set(promotionredemption.FieldChannel, v)
	return u
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *PromotionRedemptionUpsert) UpdateChannel() *PromotionRedemptionUpsert {
	u.SetExcluded(promotionredemption.FieldChannel)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *PromotionRedemptionUpsert) SetOrderID(v string) *PromotionRedemptionUpsert {
	u.Set(promotionredemption.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsert) UpdateOrderID() *PromotionRedemptionUpsert {
	u.SetExcluded(promotionredemption.FieldOrderID)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *PromotionRedemptionUpsert) SetQuantity(v float64) *PromotionRedemptionUpsert {
	u.Set(promotionredemption.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PromotionRedemptionUpsert) UpdateQuantity() *PromotionRedemptionUpsert {
	u.SetExcluded(promotionredemption.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *PromotionRedemptionUpsert) AddQuantity(v float64) *PromotionRedemptionUpsert {
	u.Add(promotionredemption.FieldQuantity, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PromotionRedemption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionredemption.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionRedemptionUpsertOne) UpdateNewValues() *PromotionRedemptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(promotionredemption.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promotionredemption.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionRedemption.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionRedemptionUpsertOne) Ignore() *PromotionRedemptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionRedemptionUpsertOne) DoNothing() *PromotionRedemptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionRedemptionCreate.OnConflict
// documentation for more info.
func (u *PromotionRedemptionUpsertOne) Update(set func(*PromotionRedemptionUpsert)) *PromotionRedemptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionRedemptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PromotionRedemptionUpsertOne) SetTenantID(v uuid.UUID) *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertOne) UpdateTenantID() *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateTenantID()
	})
}

// SetPromotionID sets the "promotion_id" field.
func (u *PromotionRedemptionUpsertOne) SetPromotionID(v uuid.UUID) *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetPromotionID(v)
	})
}

// UpdatePromotionID sets the "promotion_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertOne) UpdatePromotionID() *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdatePromotionID()
	})
}

// SetCustomerKey sets the "customer_key" field.
func (u *PromotionRedemptionUpsertOne) SetCustomerKey(v string) *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetCustomerKey(v)
	})
}

// UpdateCustomerKey sets the "customer_key" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertOne) UpdateCustomerKey() *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateCustomerKey()
	})
}

// ClearCustomerKey clears the value of the "customer_key" field.
func (u *PromotionRedemptionUpsertOne) ClearCustomerKey() *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.ClearCustomerKey()
	})
}

// SetChannel sets the "channel" field.
func (u *PromotionRedemptionUpsertOne) SetChannel(v promotionredemption.Channel) *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertOne) UpdateChannel() *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateChannel()
	})
}

// SetOrderID sets the "order_id" field.
func (u *PromotionRedemptionUpsertOne) SetOrderID(v string) *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertOne) UpdateOrderID() *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateOrderID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *PromotionRedemptionUpsertOne) SetQuantity(v float64) *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *PromotionRedemptionUpsertOne) AddQuantity(v float64) *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertOne) UpdateQuantity() *PromotionRedemptionUpsertOne {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateQuantity()
	})
}

// Exec executes the query.
func (u *PromotionRedemptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionRedemptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionRedemptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionRedemptionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PromotionRedemptionUpsertOne.ID is not supported by MySQL driver. Use PromotionRedemptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionRedemptionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionRedemptionCreateBulk is the builder for creating many PromotionRedemption entities in bulk.
type PromotionRedemptionCreateBulk struct {
	config
	err      error
	builders []*PromotionRedemptionCreate
	conflict []sql.ConflictOption
}

// Save creates the PromotionRedemption entities in the database.
func (_c *PromotionRedemptionCreateBulk) Save(ctx context.Context) ([]*PromotionRedemption, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromotionRedemption, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionRedemptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionRedemptionCreateBulk) SaveX(ctx context.Context) []*PromotionRedemption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionRedemptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionRedemptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromotionRedemption.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionRedemptionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionRedemptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionRedemptionUpsertBulk {
	_c.conflict = opts
	return &PromotionRedemptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromotionRedemption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionRedemptionCreateBulk) OnConflictColumns(columns ...string) *PromotionRedemptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionRedemptionUpsertBulk{
		create: _c,
	}
}

// PromotionRedemptionUpsertBulk is the builder for "upsert"-ing
// a bulk of PromotionRedemption nodes.
type PromotionRedemptionUpsertBulk struct {
	create *PromotionRedemptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromotionRedemption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotionredemption.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionRedemptionUpsertBulk) UpdateNewValues() *PromotionRedemptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(promotionredemption.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promotionredemption.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromotionRedemption.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionRedemptionUpsertBulk) Ignore() *PromotionRedemptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionRedemptionUpsertBulk) DoNothing() *PromotionRedemptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionRedemptionCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionRedemptionUpsertBulk) Update(set func(*PromotionRedemptionUpsert)) *PromotionRedemptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionRedemptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PromotionRedemptionUpsertBulk) SetTenantID(v uuid.UUID) *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertBulk) UpdateTenantID() *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateTenantID()
	})
}

// SetPromotionID sets the "promotion_id" field.
func (u *PromotionRedemptionUpsertBulk) SetPromotionID(v uuid.UUID) *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetPromotionID(v)
	})
}

// UpdatePromotionID sets the "promotion_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertBulk) UpdatePromotionID() *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdatePromotionID()
	})
}

// SetCustomerKey sets the "customer_key" field.
func (u *PromotionRedemptionUpsertBulk) SetCustomerKey(v string) *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetCustomerKey(v)
	})
}

// UpdateCustomerKey sets the "customer_key" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertBulk) UpdateCustomerKey() *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateCustomerKey()
	})
}

// ClearCustomerKey clears the value of the "customer_key" field.
func (u *PromotionRedemptionUpsertBulk) ClearCustomerKey() *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.ClearCustomerKey()
	})
}

// SetChannel sets the "channel" field.
func (u *PromotionRedemptionUpsertBulk) SetChannel(v promotionredemption.Channel) *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertBulk) UpdateChannel() *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateChannel()
	})
}

// SetOrderID sets the "order_id" field.
func (u *PromotionRedemptionUpsertBulk) SetOrderID(v string) *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertBulk) UpdateOrderID() *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateOrderID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *PromotionRedemptionUpsertBulk) SetQuantity(v float64) *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *PromotionRedemptionUpsertBulk) AddQuantity(v float64) *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *PromotionRedemptionUpsertBulk) UpdateQuantity() *PromotionRedemptionUpsertBulk {
	return u.Update(func(s *PromotionRedemptionUpsert) {
		s.UpdateQuantity()
	})
}

// Exec executes the query.
func (u *PromotionRedemptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionRedemptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionRedemptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionRedemptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
