// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/promotion"
	"github.com/google/uuid"
)

// PromotionCreate is the builder for creating a Promotion entity.
type PromotionCreate struct {
	config
	mutation *PromotionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *PromotionCreate) SetTenantID(v uuid.UUID) *PromotionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetOutletID sets the "outlet_id" field.
func (_c *PromotionCreate) SetOutletID(v uuid.UUID) *PromotionCreate {
	_c.mutation.SetOutletID(v)
	return _c
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableOutletID(v *uuid.UUID) *PromotionCreate {
	if v != nil {
		_c.SetOutletID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PromotionCreate) SetName(v string) *PromotionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PromotionCreate) SetDescription(v string) *PromotionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableDescription(v *string) *PromotionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPromoCode sets the "promo_code" field.
func (_c *PromotionCreate) SetPromoCode(v string) *PromotionCreate {
	_c.mutation.SetPromoCode(v)
	return _c
}

// SetNillablePromoCode sets the "promo_code" field if the given value is not nil.
func (_c *PromotionCreate) SetNillablePromoCode(v *string) *PromotionCreate {
	if v != nil {
		_c.SetPromoCode(*v)
	}
	return _c
}

// SetPromoKind sets the "promo_kind" field.
func (_c *PromotionCreate) SetPromoKind(v promotion.PromoKind) *PromotionCreate {
	_c.mutation.SetPromoKind(v)
	return _c
}

// SetNillablePromoKind sets the "promo_kind" field if the given value is not nil.
func (_c *PromotionCreate) SetNillablePromoKind(v *promotion.PromoKind) *PromotionCreate {
	if v != nil {
		_c.SetPromoKind(*v)
	}
	return _c
}

// SetDaysOfWeek sets the "days_of_week" field.
func (_c *PromotionCreate) SetDaysOfWeek(v []int) *PromotionCreate {
	_c.mutation.SetDaysOfWeek(v)
	return _c
}

// SetWindowStart sets the "window_start" field.
func (_c *PromotionCreate) SetWindowStart(v string) *PromotionCreate {
	_c.mutation.SetWindowStart(v)
	return _c
}

// SetNillableWindowStart sets the "window_start" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableWindowStart(v *string) *PromotionCreate {
	if v != nil {
		_c.SetWindowStart(*v)
	}
	return _c
}

// SetWindowEnd sets the "window_end" field.
func (_c *PromotionCreate) SetWindowEnd(v string) *PromotionCreate {
	_c.mutation.SetWindowEnd(v)
	return _c
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableWindowEnd(v *string) *PromotionCreate {
	if v != nil {
		_c.SetWindowEnd(*v)
	}
	return _c
}

// SetAutoApply sets the "auto_apply" field.
func (_c *PromotionCreate) SetAutoApply(v bool) *PromotionCreate {
	_c.mutation.SetAutoApply(v)
	return _c
}

// SetNillableAutoApply sets the "auto_apply" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableAutoApply(v *bool) *PromotionCreate {
	if v != nil {
		_c.SetAutoApply(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PromotionCreate) SetStatus(v string) *PromotionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableStatus(v *string) *PromotionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *PromotionCreate) SetStartAt(v time.Time) *PromotionCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableStartAt(v *time.Time) *PromotionCreate {
	if v != nil {
		_c.SetStartAt(*v)
	}
	return _c
}

// SetEndAt sets the "end_at" field.
func (_c *PromotionCreate) SetEndAt(v time.Time) *PromotionCreate {
	_c.mutation.SetEndAt(v)
	return _c
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableEndAt(v *time.Time) *PromotionCreate {
	if v != nil {
		_c.SetEndAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *PromotionCreate) SetMetadata(v map[string]interface{}) *PromotionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetUsageLimit sets the "usage_limit" field.
func (_c *PromotionCreate) SetUsageLimit(v int) *PromotionCreate {
	_c.mutation.SetUsageLimit(v)
	return _c
}

// SetNillableUsageLimit sets the "usage_limit" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableUsageLimit(v *int) *PromotionCreate {
	if v != nil {
		_c.SetUsageLimit(*v)
	}
	return _c
}

// SetMaxUnitsPerCustomer sets the "max_units_per_customer" field.
func (_c *PromotionCreate) SetMaxUnitsPerCustomer(v int) *PromotionCreate {
	_c.mutation.SetMaxUnitsPerCustomer(v)
	return _c
}

// SetNillableMaxUnitsPerCustomer sets the "max_units_per_customer" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableMaxUnitsPerCustomer(v *int) *PromotionCreate {
	if v != nil {
		_c.SetMaxUnitsPerCustomer(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PromotionCreate) SetID(v uuid.UUID) *PromotionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PromotionCreate) SetNillableID(v *uuid.UUID) *PromotionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PromotionMutation object of the builder.
func (_c *PromotionCreate) Mutation() *PromotionMutation {
	return _c.mutation
}

// Save creates the Promotion in the database.
func (_c *PromotionCreate) Save(ctx context.Context) (*Promotion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromotionCreate) SaveX(ctx context.Context) *Promotion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromotionCreate) defaults() {
	if _, ok := _c.mutation.PromoKind(); !ok {
		v := promotion.DefaultPromoKind
		_c.mutation.SetPromoKind(v)
	}
	if _, ok := _c.mutation.AutoApply(); !ok {
		v := promotion.DefaultAutoApply
		_c.mutation.SetAutoApply(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := promotion.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StartAt(); !ok {
		v := promotion.DefaultStartAt()
		_c.mutation.SetStartAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := promotion.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := promotion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromotionCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Promotion.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Promotion.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := promotion.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Promotion.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromoKind(); !ok {
		return &ValidationError{Name: "promo_kind", err: errors.New(`ent: missing required field "Promotion.promo_kind"`)}
	}
	if v, ok := _c.mutation.PromoKind(); ok {
		if err := promotion.PromoKindValidator(v); err != nil {
			return &ValidationError{Name: "promo_kind", err: fmt.Errorf(`ent: validator failed for field "Promotion.promo_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AutoApply(); !ok {
		return &ValidationError{Name: "auto_apply", err: errors.New(`ent: missing required field "Promotion.auto_apply"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Promotion.status"`)}
	}
	if _, ok := _c.mutation.StartAt(); !ok {
		return &ValidationError{Name: "start_at", err: errors.New(`ent: missing required field "Promotion.start_at"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Promotion.metadata"`)}
	}
	return nil
}

func (_c *PromotionCreate) sqlSave(ctx context.Context) (*Promotion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromotionCreate) createSpec() (*Promotion, *sqlgraph.CreateSpec) {
	var (
		_node = &Promotion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promotion.Table, sqlgraph.NewFieldSpec(promotion.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(promotion.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.OutletID(); ok {
		_spec.SetField(promotion.FieldOutletID, field.TypeUUID, value)
		_node.OutletID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(promotion.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(promotion.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PromoCode(); ok {
		_spec.SetField(promotion.FieldPromoCode, field.TypeString, value)
		_node.PromoCode = &value
	}
	if value, ok := _c.mutation.PromoKind(); ok {
		_spec.SetField(promotion.FieldPromoKind, field.TypeEnum, value)
		_node.PromoKind = value
	}
	if value, ok := _c.mutation.DaysOfWeek(); ok {
		_spec.SetField(promotion.FieldDaysOfWeek, field.TypeJSON, value)
		_node.DaysOfWeek = value
	}
	if value, ok := _c.mutation.WindowStart(); ok {
		_spec.SetField(promotion.FieldWindowStart, field.TypeString, value)
		_node.WindowStart = value
	}
	if value, ok := _c.mutation.WindowEnd(); ok {
		_spec.SetField(promotion.FieldWindowEnd, field.TypeString, value)
		_node.WindowEnd = value
	}
	if value, ok := _c.mutation.AutoApply(); ok {
		_spec.SetField(promotion.FieldAutoApply, field.TypeBool, value)
		_node.AutoApply = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(promotion.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(promotion.FieldStartAt, field.TypeTime, value)
		_node.StartAt = value
	}
	if value, ok := _c.mutation.EndAt(); ok {
		_spec.SetField(promotion.FieldEndAt, field.TypeTime, value)
		_node.EndAt = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(promotion.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.UsageLimit(); ok {
		_spec.SetField(promotion.FieldUsageLimit, field.TypeInt, value)
		_node.UsageLimit = &value
	}
	if value, ok := _c.mutation.MaxUnitsPerCustomer(); ok {
		_spec.SetField(promotion.FieldMaxUnitsPerCustomer, field.TypeInt, value)
		_node.MaxUnitsPerCustomer = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Promotion.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionCreate) OnConflict(opts ...sql.ConflictOption) *PromotionUpsertOne {
	_c.conflict = opts
	return &PromotionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Promotion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionCreate) OnConflictColumns(columns ...string) *PromotionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionUpsertOne{
		create: _c,
	}
}

type (
	// PromotionUpsertOne is the builder for "upsert"-ing
	//  one Promotion node.
	PromotionUpsertOne struct {
		create *PromotionCreate
	}

	// PromotionUpsert is the "OnConflict" setter.
	PromotionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *PromotionUpsert) SetTenantID(v uuid.UUID) *PromotionUpsert {
	u.Set(promotion.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateTenantID() *PromotionUpsert {
	u.SetExcluded(promotion.FieldTenantID)
	return u
}

// SetOutletID sets the "outlet_id" field.
func (u *PromotionUpsert) SetOutletID(v uuid.UUID) *PromotionUpsert {
	u.Set(promotion.FieldOutletID, v)
	return u
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateOutletID() *PromotionUpsert {
	u.SetExcluded(promotion.FieldOutletID)
	return u
}

// ClearOutletID clears the value of the "outlet_id" field.
func (u *PromotionUpsert) ClearOutletID() *PromotionUpsert {
	u.SetNull(promotion.FieldOutletID)
	return u
}

// SetName sets the "name" field.
func (u *PromotionUpsert) SetName(v string) *PromotionUpsert {
	u.Set(promotion.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateName() *PromotionUpsert {
	u.SetExcluded(promotion.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *PromotionUpsert) SetDescription(v string) *PromotionUpsert {
	u.Set(promotion.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateDescription() *PromotionUpsert {
	u.SetExcluded(promotion.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *PromotionUpsert) ClearDescription() *PromotionUpsert {
	u.SetNull(promotion.FieldDescription)
	return u
}

// SetPromoCode sets the "promo_code" field.
func (u *PromotionUpsert) SetPromoCode(v string) *PromotionUpsert {
	u.Set(promotion.FieldPromoCode, v)
	return u
}

// UpdatePromoCode sets the "promo_code" field to the value that was provided on create.
func (u *PromotionUpsert) UpdatePromoCode() *PromotionUpsert {
	u.SetExcluded(promotion.FieldPromoCode)
	return u
}

// ClearPromoCode clears the value of the "promo_code" field.
func (u *PromotionUpsert) ClearPromoCode() *PromotionUpsert {
	u.SetNull(promotion.FieldPromoCode)
	return u
}

// SetPromoKind sets the "promo_kind" field.
func (u *PromotionUpsert) SetPromoKind(v promotion.PromoKind) *PromotionUpsert {
	u.Set(promotion.FieldPromoKind, v)
	return u
}

// UpdatePromoKind sets the "promo_kind" field to the value that was provided on create.
func (u *PromotionUpsert) UpdatePromoKind() *PromotionUpsert {
	u.SetExcluded(promotion.FieldPromoKind)
	return u
}

// SetDaysOfWeek sets the "days_of_week" field.
func (u *PromotionUpsert) SetDaysOfWeek(v []int) *PromotionUpsert {
	u.Set(promotion.FieldDaysOfWeek, v)
	return u
}

// UpdateDaysOfWeek sets the "days_of_week" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateDaysOfWeek() *PromotionUpsert {
	u.SetExcluded(promotion.FieldDaysOfWeek)
	return u
}

// ClearDaysOfWeek clears the value of the "days_of_week" field.
func (u *PromotionUpsert) ClearDaysOfWeek() *PromotionUpsert {
	u.SetNull(promotion.FieldDaysOfWeek)
	return u
}

// SetWindowStart sets the "window_start" field.
func (u *PromotionUpsert) SetWindowStart(v string) *PromotionUpsert {
	u.Set(promotion.FieldWindowStart, v)
	return u
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateWindowStart() *PromotionUpsert {
	u.SetExcluded(promotion.FieldWindowStart)
	return u
}

// ClearWindowStart clears the value of the "window_start" field.
func (u *PromotionUpsert) ClearWindowStart() *PromotionUpsert {
	u.SetNull(promotion.FieldWindowStart)
	return u
}

// SetWindowEnd sets the "window_end" field.
func (u *PromotionUpsert) SetWindowEnd(v string) *PromotionUpsert {
	u.Set(promotion.FieldWindowEnd, v)
	return u
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateWindowEnd() *PromotionUpsert {
	u.SetExcluded(promotion.FieldWindowEnd)
	return u
}

// ClearWindowEnd clears the value of the "window_end" field.
func (u *PromotionUpsert) ClearWindowEnd() *PromotionUpsert {
	u.SetNull(promotion.FieldWindowEnd)
	return u
}

// SetAutoApply sets the "auto_apply" field.
func (u *PromotionUpsert) SetAutoApply(v bool) *PromotionUpsert {
	u.Set(promotion.FieldAutoApply, v)
	return u
}

// UpdateAutoApply sets the "auto_apply" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateAutoApply() *PromotionUpsert {
	u.SetExcluded(promotion.FieldAutoApply)
	return u
}

// SetStatus sets the "status" field.
func (u *PromotionUpsert) SetStatus(v string) *PromotionUpsert {
	u.Set(promotion.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateStatus() *PromotionUpsert {
	u.SetExcluded(promotion.FieldStatus)
	return u
}

// SetStartAt sets the "start_at" field.
func (u *PromotionUpsert) SetStartAt(v time.Time) *PromotionUpsert {
	u.Set(promotion.FieldStartAt, v)
	return u
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateStartAt() *PromotionUpsert {
	u.SetExcluded(promotion.FieldStartAt)
	return u
}

// SetEndAt sets the "end_at" field.
func (u *PromotionUpsert) SetEndAt(v time.Time) *PromotionUpsert {
	u.Set(promotion.FieldEndAt, v)
	return u
}

// UpdateEndAt sets the "end_at" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateEndAt() *PromotionUpsert {
	u.SetExcluded(promotion.FieldEndAt)
	return u
}

// ClearEndAt clears the value of the "end_at" field.
func (u *PromotionUpsert) ClearEndAt() *PromotionUpsert {
	u.SetNull(promotion.FieldEndAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *PromotionUpsert) SetMetadata(v map[string]interface{}) *PromotionUpsert {
	u.Set(promotion.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateMetadata() *PromotionUpsert {
	u.SetExcluded(promotion.FieldMetadata)
	return u
}

// SetUsageLimit sets the "usage_limit" field.
func (u *PromotionUpsert) SetUsageLimit(v int) *PromotionUpsert {
	u.Set(promotion.FieldUsageLimit, v)
	return u
}

// UpdateUsageLimit sets the "usage_limit" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateUsageLimit() *PromotionUpsert {
	u.SetExcluded(promotion.FieldUsageLimit)
	return u
}

// AddUsageLimit adds v to the "usage_limit" field.
func (u *PromotionUpsert) AddUsageLimit(v int) *PromotionUpsert {
	u.Add(promotion.FieldUsageLimit, v)
	return u
}

// ClearUsageLimit clears the value of the "usage_limit" field.
func (u *PromotionUpsert) ClearUsageLimit() *PromotionUpsert {
	u.SetNull(promotion.FieldUsageLimit)
	return u
}

// SetMaxUnitsPerCustomer sets the "max_units_per_customer" field.
func (u *PromotionUpsert) SetMaxUnitsPerCustomer(v int) *PromotionUpsert {
	u.Set(promotion.FieldMaxUnitsPerCustomer, v)
	return u
}

// UpdateMaxUnitsPerCustomer sets the "max_units_per_customer" field to the value that was provided on create.
func (u *PromotionUpsert) UpdateMaxUnitsPerCustomer() *PromotionUpsert {
	u.SetExcluded(promotion.FieldMaxUnitsPerCustomer)
	return u
}

// AddMaxUnitsPerCustomer adds v to the "max_units_per_customer" field.
func (u *PromotionUpsert) AddMaxUnitsPerCustomer(v int) *PromotionUpsert {
	u.Add(promotion.FieldMaxUnitsPerCustomer, v)
	return u
}

// ClearMaxUnitsPerCustomer clears the value of the "max_units_per_customer" field.
func (u *PromotionUpsert) ClearMaxUnitsPerCustomer() *PromotionUpsert {
	u.SetNull(promotion.FieldMaxUnitsPerCustomer)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Promotion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionUpsertOne) UpdateNewValues() *PromotionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(promotion.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Promotion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromotionUpsertOne) Ignore() *PromotionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionUpsertOne) DoNothing() *PromotionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionCreate.OnConflict
// documentation for more info.
func (u *PromotionUpsertOne) Update(set func(*PromotionUpsert)) *PromotionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PromotionUpsertOne) SetTenantID(v uuid.UUID) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateTenantID() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateTenantID()
	})
}

// SetOutletID sets the "outlet_id" field.
func (u *PromotionUpsertOne) SetOutletID(v uuid.UUID) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetOutletID(v)
	})
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateOutletID() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateOutletID()
	})
}

// ClearOutletID clears the value of the "outlet_id" field.
func (u *PromotionUpsertOne) ClearOutletID() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearOutletID()
	})
}

// SetName sets the "name" field.
func (u *PromotionUpsertOne) SetName(v string) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateName() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *PromotionUpsertOne) SetDescription(v string) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateDescription() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PromotionUpsertOne) ClearDescription() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearDescription()
	})
}

// SetPromoCode sets the "promo_code" field.
func (u *PromotionUpsertOne) SetPromoCode(v string) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetPromoCode(v)
	})
}

// UpdatePromoCode sets the "promo_code" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdatePromoCode() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdatePromoCode()
	})
}

// ClearPromoCode clears the value of the "promo_code" field.
func (u *PromotionUpsertOne) ClearPromoCode() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearPromoCode()
	})
}

// SetPromoKind sets the "promo_kind" field.
func (u *PromotionUpsertOne) SetPromoKind(v promotion.PromoKind) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetPromoKind(v)
	})
}

// UpdatePromoKind sets the "promo_kind" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdatePromoKind() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdatePromoKind()
	})
}

// SetDaysOfWeek sets the "days_of_week" field.
func (u *PromotionUpsertOne) SetDaysOfWeek(v []int) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetDaysOfWeek(v)
	})
}

// UpdateDaysOfWeek sets the "days_of_week" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateDaysOfWeek() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateDaysOfWeek()
	})
}

// ClearDaysOfWeek clears the value of the "days_of_week" field.
func (u *PromotionUpsertOne) ClearDaysOfWeek() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearDaysOfWeek()
	})
}

// SetWindowStart sets the "window_start" field.
func (u *PromotionUpsertOne) SetWindowStart(v string) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetWindowStart(v)
	})
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateWindowStart() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateWindowStart()
	})
}

// ClearWindowStart clears the value of the "window_start" field.
func (u *PromotionUpsertOne) ClearWindowStart() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearWindowStart()
	})
}

// SetWindowEnd sets the "window_end" field.
func (u *PromotionUpsertOne) SetWindowEnd(v string) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetWindowEnd(v)
	})
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateWindowEnd() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateWindowEnd()
	})
}

// ClearWindowEnd clears the value of the "window_end" field.
func (u *PromotionUpsertOne) ClearWindowEnd() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearWindowEnd()
	})
}

// SetAutoApply sets the "auto_apply" field.
func (u *PromotionUpsertOne) SetAutoApply(v bool) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetAutoApply(v)
	})
}

// UpdateAutoApply sets the "auto_apply" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateAutoApply() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateAutoApply()
	})
}

// SetStatus sets the "status" field.
func (u *PromotionUpsertOne) SetStatus(v string) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateStatus() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateStatus()
	})
}

// SetStartAt sets the "start_at" field.
func (u *PromotionUpsertOne) SetStartAt(v time.Time) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetStartAt(v)
	})
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateStartAt() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateStartAt()
	})
}

// SetEndAt sets the "end_at" field.
func (u *PromotionUpsertOne) SetEndAt(v time.Time) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetEndAt(v)
	})
}

// UpdateEndAt sets the "end_at" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateEndAt() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateEndAt()
	})
}

// ClearEndAt clears the value of the "end_at" field.
func (u *PromotionUpsertOne) ClearEndAt() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearEndAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *PromotionUpsertOne) SetMetadata(v map[string]interface{}) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateMetadata() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateMetadata()
	})
}

// SetUsageLimit sets the "usage_limit" field.
func (u *PromotionUpsertOne) SetUsageLimit(v int) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetUsageLimit(v)
	})
}

// AddUsageLimit adds v to the "usage_limit" field.
func (u *PromotionUpsertOne) AddUsageLimit(v int) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.AddUsageLimit(v)
	})
}

// UpdateUsageLimit sets the "usage_limit" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateUsageLimit() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateUsageLimit()
	})
}

// ClearUsageLimit clears the value of the "usage_limit" field.
func (u *PromotionUpsertOne) ClearUsageLimit() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearUsageLimit()
	})
}

// SetMaxUnitsPerCustomer sets the "max_units_per_customer" field.
func (u *PromotionUpsertOne) SetMaxUnitsPerCustomer(v int) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.SetMaxUnitsPerCustomer(v)
	})
}

// AddMaxUnitsPerCustomer adds v to the "max_units_per_customer" field.
func (u *PromotionUpsertOne) AddMaxUnitsPerCustomer(v int) *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.AddMaxUnitsPerCustomer(v)
	})
}

// UpdateMaxUnitsPerCustomer sets the "max_units_per_customer" field to the value that was provided on create.
func (u *PromotionUpsertOne) UpdateMaxUnitsPerCustomer() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateMaxUnitsPerCustomer()
	})
}

// ClearMaxUnitsPerCustomer clears the value of the "max_units_per_customer" field.
func (u *PromotionUpsertOne) ClearMaxUnitsPerCustomer() *PromotionUpsertOne {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearMaxUnitsPerCustomer()
	})
}

// Exec executes the query.
func (u *PromotionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromotionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PromotionUpsertOne.ID is not supported by MySQL driver. Use PromotionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromotionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromotionCreateBulk is the builder for creating many Promotion entities in bulk.
type PromotionCreateBulk struct {
	config
	err      error
	builders []*PromotionCreate
	conflict []sql.ConflictOption
}

// Save creates the Promotion entities in the database.
func (_c *PromotionCreateBulk) Save(ctx context.Context) ([]*Promotion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Promotion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromotionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromotionCreateBulk) SaveX(ctx context.Context) []*Promotion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromotionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromotionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Promotion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromotionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PromotionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromotionUpsertBulk {
	_c.conflict = opts
	return &PromotionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Promotion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromotionCreateBulk) OnConflictColumns(columns ...string) *PromotionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromotionUpsertBulk{
		create: _c,
	}
}

// PromotionUpsertBulk is the builder for "upsert"-ing
// a bulk of Promotion nodes.
type PromotionUpsertBulk struct {
	create *PromotionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Promotion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(promotion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PromotionUpsertBulk) UpdateNewValues() *PromotionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(promotion.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Promotion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromotionUpsertBulk) Ignore() *PromotionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromotionUpsertBulk) DoNothing() *PromotionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromotionCreateBulk.OnConflict
// documentation for more info.
func (u *PromotionUpsertBulk) Update(set func(*PromotionUpsert)) *PromotionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromotionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PromotionUpsertBulk) SetTenantID(v uuid.UUID) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateTenantID() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateTenantID()
	})
}

// SetOutletID sets the "outlet_id" field.
func (u *PromotionUpsertBulk) SetOutletID(v uuid.UUID) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetOutletID(v)
	})
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateOutletID() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateOutletID()
	})
}

// ClearOutletID clears the value of the "outlet_id" field.
func (u *PromotionUpsertBulk) ClearOutletID() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearOutletID()
	})
}

// SetName sets the "name" field.
func (u *PromotionUpsertBulk) SetName(v string) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateName() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *PromotionUpsertBulk) SetDescription(v string) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateDescription() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PromotionUpsertBulk) ClearDescription() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearDescription()
	})
}

// SetPromoCode sets the "promo_code" field.
func (u *PromotionUpsertBulk) SetPromoCode(v string) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetPromoCode(v)
	})
}

// UpdatePromoCode sets the "promo_code" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdatePromoCode() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdatePromoCode()
	})
}

// ClearPromoCode clears the value of the "promo_code" field.
func (u *PromotionUpsertBulk) ClearPromoCode() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearPromoCode()
	})
}

// SetPromoKind sets the "promo_kind" field.
func (u *PromotionUpsertBulk) SetPromoKind(v promotion.PromoKind) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetPromoKind(v)
	})
}

// UpdatePromoKind sets the "promo_kind" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdatePromoKind() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdatePromoKind()
	})
}

// SetDaysOfWeek sets the "days_of_week" field.
func (u *PromotionUpsertBulk) SetDaysOfWeek(v []int) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetDaysOfWeek(v)
	})
}

// UpdateDaysOfWeek sets the "days_of_week" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateDaysOfWeek() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateDaysOfWeek()
	})
}

// ClearDaysOfWeek clears the value of the "days_of_week" field.
func (u *PromotionUpsertBulk) ClearDaysOfWeek() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearDaysOfWeek()
	})
}

// SetWindowStart sets the "window_start" field.
func (u *PromotionUpsertBulk) SetWindowStart(v string) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetWindowStart(v)
	})
}

// UpdateWindowStart sets the "window_start" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateWindowStart() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateWindowStart()
	})
}

// ClearWindowStart clears the value of the "window_start" field.
func (u *PromotionUpsertBulk) ClearWindowStart() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearWindowStart()
	})
}

// SetWindowEnd sets the "window_end" field.
func (u *PromotionUpsertBulk) SetWindowEnd(v string) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetWindowEnd(v)
	})
}

// UpdateWindowEnd sets the "window_end" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateWindowEnd() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateWindowEnd()
	})
}

// ClearWindowEnd clears the value of the "window_end" field.
func (u *PromotionUpsertBulk) ClearWindowEnd() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearWindowEnd()
	})
}

// SetAutoApply sets the "auto_apply" field.
func (u *PromotionUpsertBulk) SetAutoApply(v bool) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetAutoApply(v)
	})
}

// UpdateAutoApply sets the "auto_apply" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateAutoApply() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateAutoApply()
	})
}

// SetStatus sets the "status" field.
func (u *PromotionUpsertBulk) SetStatus(v string) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateStatus() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateStatus()
	})
}

// SetStartAt sets the "start_at" field.
func (u *PromotionUpsertBulk) SetStartAt(v time.Time) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetStartAt(v)
	})
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateStartAt() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateStartAt()
	})
}

// SetEndAt sets the "end_at" field.
func (u *PromotionUpsertBulk) SetEndAt(v time.Time) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetEndAt(v)
	})
}

// UpdateEndAt sets the "end_at" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateEndAt() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateEndAt()
	})
}

// ClearEndAt clears the value of the "end_at" field.
func (u *PromotionUpsertBulk) ClearEndAt() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearEndAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *PromotionUpsertBulk) SetMetadata(v map[string]interface{}) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateMetadata() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateMetadata()
	})
}

// SetUsageLimit sets the "usage_limit" field.
func (u *PromotionUpsertBulk) SetUsageLimit(v int) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetUsageLimit(v)
	})
}

// AddUsageLimit adds v to the "usage_limit" field.
func (u *PromotionUpsertBulk) AddUsageLimit(v int) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.AddUsageLimit(v)
	})
}

// UpdateUsageLimit sets the "usage_limit" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateUsageLimit() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateUsageLimit()
	})
}

// ClearUsageLimit clears the value of the "usage_limit" field.
func (u *PromotionUpsertBulk) ClearUsageLimit() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearUsageLimit()
	})
}

// SetMaxUnitsPerCustomer sets the "max_units_per_customer" field.
func (u *PromotionUpsertBulk) SetMaxUnitsPerCustomer(v int) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.SetMaxUnitsPerCustomer(v)
	})
}

// AddMaxUnitsPerCustomer adds v to the "max_units_per_customer" field.
func (u *PromotionUpsertBulk) AddMaxUnitsPerCustomer(v int) *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.AddMaxUnitsPerCustomer(v)
	})
}

// UpdateMaxUnitsPerCustomer sets the "max_units_per_customer" field to the value that was provided on create.
func (u *PromotionUpsertBulk) UpdateMaxUnitsPerCustomer() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.UpdateMaxUnitsPerCustomer()
	})
}

// ClearMaxUnitsPerCustomer clears the value of the "max_units_per_customer" field.
func (u *PromotionUpsertBulk) ClearMaxUnitsPerCustomer() *PromotionUpsertBulk {
	return u.Update(func(s *PromotionUpsert) {
		s.ClearMaxUnitsPerCustomer()
	})
}

// Exec executes the query.
func (u *PromotionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromotionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromotionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromotionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
