// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/promotionredemption"
	"github.com/google/uuid"
)

// PromotionRedemption is the model entity for the PromotionRedemption schema.
type PromotionRedemption struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// PromotionID holds the value of the "promotion_id" field.
	PromotionID uuid.UUID `json:"promotion_id,omitempty"`
	// Phone/customer-id/loyalty key identifying who redeemed; empty = anonymous/unknown (still counts toward the total cap, exempt from the per-customer cap)
	CustomerKey string `json:"customer_key,omitempty"`
	// Which checkout surface this redemption came from
	Channel promotionredemption.Channel `json:"channel,omitempty"`
	// Caller-supplied idempotency anchor: pos-api's client_reference/order_number (order not yet created when reserved), or ordering-backend's order/reservation reference. Plain string, not a foreign key -- the two channels use different id shapes.
	OrderID string `json:"order_id,omitempty"`
	// Units redeemed in this reservation; summed against usage_limit/max_units_per_customer
	Quantity float64 `json:"quantity,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromotionRedemption) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promotionredemption.FieldQuantity:
			values[i] = new(sql.NullFloat64)
		case promotionredemption.FieldCustomerKey, promotionredemption.FieldChannel, promotionredemption.FieldOrderID:
			values[i] = new(sql.NullString)
		case promotionredemption.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case promotionredemption.FieldID, promotionredemption.FieldTenantID, promotionredemption.FieldPromotionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromotionRedemption fields.
func (_m *PromotionRedemption) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promotionredemption.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case promotionredemption.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case promotionredemption.FieldPromotionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field promotion_id", values[i])
			} else if value != nil {
				_m.PromotionID = *value
			}
		case promotionredemption.FieldCustomerKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_key", values[i])
			} else if value.Valid {
				_m.CustomerKey = value.String
			}
		case promotionredemption.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = promotionredemption.Channel(value.String)
			}
		case promotionredemption.FieldOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.String
			}
		case promotionredemption.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case promotionredemption.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromotionRedemption.
// This includes values selected through modifiers, order, etc.
func (_m *PromotionRedemption) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PromotionRedemption.
// Note that you need to call PromotionRedemption.Unwrap() before calling this method if this PromotionRedemption
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromotionRedemption) Update() *PromotionRedemptionUpdateOne {
	return NewPromotionRedemptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromotionRedemption entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromotionRedemption) Unwrap() *PromotionRedemption {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromotionRedemption is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromotionRedemption) String() string {
	var builder strings.Builder
	builder.WriteString("PromotionRedemption(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("promotion_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromotionID))
	builder.WriteString(", ")
	builder.WriteString("customer_key=")
	builder.WriteString(_m.CustomerKey)
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(fmt.Sprintf("%v", _m.Channel))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(_m.OrderID)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PromotionRedemptions is a parsable slice of PromotionRedemption.
type PromotionRedemptions []*PromotionRedemption
