// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// Appointment is the client for interacting with the Appointment builders.
	Appointment *AppointmentClient
	// AuditLog is the client for interacting with the AuditLog builders.
	AuditLog *AuditLogClient
	// Backup is the client for interacting with the Backup builders.
	Backup *BackupClient
	// BackupSetting is the client for interacting with the BackupSetting builders.
	BackupSetting *BackupSettingClient
	// BarTab is the client for interacting with the BarTab builders.
	BarTab *BarTabClient
	// BarTabEvent is the client for interacting with the BarTabEvent builders.
	BarTabEvent *BarTabEventClient
	// BillSplit is the client for interacting with the BillSplit builders.
	BillSplit *BillSplitClient
	// CashDrawer is the client for interacting with the CashDrawer builders.
	CashDrawer *CashDrawerClient
	// CashDrawerEvent is the client for interacting with the CashDrawerEvent builders.
	CashDrawerEvent *CashDrawerEventClient
	// ChannelIntegration is the client for interacting with the ChannelIntegration builders.
	ChannelIntegration *ChannelIntegrationClient
	// ChannelSyncJob is the client for interacting with the ChannelSyncJob builders.
	ChannelSyncJob *ChannelSyncJobClient
	// ClientRecord is the client for interacting with the ClientRecord builders.
	ClientRecord *ClientRecordClient
	// CommissionRecord is the client for interacting with the CommissionRecord builders.
	CommissionRecord *CommissionRecordClient
	// CommissionRule is the client for interacting with the CommissionRule builders.
	CommissionRule *CommissionRuleClient
	// CustomerBalanceCache is the client for interacting with the CustomerBalanceCache builders.
	CustomerBalanceCache *CustomerBalanceCacheClient
	// DailyClosing is the client for interacting with the DailyClosing builders.
	DailyClosing *DailyClosingClient
	// DocumentSequence is the client for interacting with the DocumentSequence builders.
	DocumentSequence *DocumentSequenceClient
	// EventBooking is the client for interacting with the EventBooking builders.
	EventBooking *EventBookingClient
	// Facility is the client for interacting with the Facility builders.
	Facility *FacilityClient
	// FacilityBooking is the client for interacting with the FacilityBooking builders.
	FacilityBooking *FacilityBookingClient
	// FeatureOverride is the client for interacting with the FeatureOverride builders.
	FeatureOverride *FeatureOverrideClient
	// GiftCard is the client for interacting with the GiftCard builders.
	GiftCard *GiftCardClient
	// GiftCardTransaction is the client for interacting with the GiftCardTransaction builders.
	GiftCardTransaction *GiftCardTransactionClient
	// HeldItem is the client for interacting with the HeldItem builders.
	HeldItem *HeldItemClient
	// HousekeepingTask is the client for interacting with the HousekeepingTask builders.
	HousekeepingTask *HousekeepingTaskClient
	// IdempotencyKey is the client for interacting with the IdempotencyKey builders.
	IdempotencyKey *IdempotencyKeyClient
	// IntegrationSetting is the client for interacting with the IntegrationSetting builders.
	IntegrationSetting *IntegrationSettingClient
	// InventorySnapshot is the client for interacting with the InventorySnapshot builders.
	InventorySnapshot *InventorySnapshotClient
	// KDSStation is the client for interacting with the KDSStation builders.
	KDSStation *KDSStationClient
	// KDSSyncFailure is the client for interacting with the KDSSyncFailure builders.
	KDSSyncFailure *KDSSyncFailureClient
	// KDSTicket is the client for interacting with the KDSTicket builders.
	KDSTicket *KDSTicketClient
	// LayawayPayment is the client for interacting with the LayawayPayment builders.
	LayawayPayment *LayawayPaymentClient
	// LayawayPlan is the client for interacting with the LayawayPlan builders.
	LayawayPlan *LayawayPlanClient
	// LeaveRequest is the client for interacting with the LeaveRequest builders.
	LeaveRequest *LeaveRequestClient
	// LicenseUsageSnapshot is the client for interacting with the LicenseUsageSnapshot builders.
	LicenseUsageSnapshot *LicenseUsageSnapshotClient
	// LoyaltyAccount is the client for interacting with the LoyaltyAccount builders.
	LoyaltyAccount *LoyaltyAccountClient
	// LoyaltyProgram is the client for interacting with the LoyaltyProgram builders.
	LoyaltyProgram *LoyaltyProgramClient
	// LoyaltyTransaction is the client for interacting with the LoyaltyTransaction builders.
	LoyaltyTransaction *LoyaltyTransactionClient
	// MealEntitlement is the client for interacting with the MealEntitlement builders.
	MealEntitlement *MealEntitlementClient
	// Modifier is the client for interacting with the Modifier builders.
	Modifier *ModifierClient
	// ModifierGroup is the client for interacting with the ModifierGroup builders.
	ModifierGroup *ModifierGroupClient
	// OrderLink is the client for interacting with the OrderLink builders.
	OrderLink *OrderLinkClient
	// OrderVoidCode is the client for interacting with the OrderVoidCode builders.
	OrderVoidCode *OrderVoidCodeClient
	// OutboxEvent is the client for interacting with the OutboxEvent builders.
	OutboxEvent *OutboxEventClient
	// Outlet is the client for interacting with the Outlet builders.
	Outlet *OutletClient
	// OutletSetting is the client for interacting with the OutletSetting builders.
	OutletSetting *OutletSettingClient
	// POSCatalogOverride is the client for interacting with the POSCatalogOverride builders.
	POSCatalogOverride *POSCatalogOverrideClient
	// POSDevice is the client for interacting with the POSDevice builders.
	POSDevice *POSDeviceClient
	// POSDeviceSession is the client for interacting with the POSDeviceSession builders.
	POSDeviceSession *POSDeviceSessionClient
	// POSLineModifier is the client for interacting with the POSLineModifier builders.
	POSLineModifier *POSLineModifierClient
	// POSOrder is the client for interacting with the POSOrder builders.
	POSOrder *POSOrderClient
	// POSOrderEvent is the client for interacting with the POSOrderEvent builders.
	POSOrderEvent *POSOrderEventClient
	// POSOrderLine is the client for interacting with the POSOrderLine builders.
	POSOrderLine *POSOrderLineClient
	// POSPayment is the client for interacting with the POSPayment builders.
	POSPayment *POSPaymentClient
	// POSPermission is the client for interacting with the POSPermission builders.
	POSPermission *POSPermissionClient
	// POSRefund is the client for interacting with the POSRefund builders.
	POSRefund *POSRefundClient
	// POSReturn is the client for interacting with the POSReturn builders.
	POSReturn *POSReturnClient
	// POSReturnLine is the client for interacting with the POSReturnLine builders.
	POSReturnLine *POSReturnLineClient
	// POSReversal is the client for interacting with the POSReversal builders.
	POSReversal *POSReversalClient
	// POSRole is the client for interacting with the POSRole builders.
	POSRole *POSRoleClient
	// POSRolePermission is the client for interacting with the POSRolePermission builders.
	POSRolePermission *POSRolePermissionClient
	// POSRoleV2 is the client for interacting with the POSRoleV2 builders.
	POSRoleV2 *POSRoleV2Client
	// POSSaleEdit is the client for interacting with the POSSaleEdit builders.
	POSSaleEdit *POSSaleEditClient
	// POSSaleShred is the client for interacting with the POSSaleShred builders.
	POSSaleShred *POSSaleShredClient
	// POSUserRoleAssignment is the client for interacting with the POSUserRoleAssignment builders.
	POSUserRoleAssignment *POSUserRoleAssignmentClient
	// PosNotification is the client for interacting with the PosNotification builders.
	PosNotification *PosNotificationClient
	// PriceBook is the client for interacting with the PriceBook builders.
	PriceBook *PriceBookClient
	// PriceBookItem is the client for interacting with the PriceBookItem builders.
	PriceBookItem *PriceBookItemClient
	// PrintAgent is the client for interacting with the PrintAgent builders.
	PrintAgent *PrintAgentClient
	// PrintJob is the client for interacting with the PrintJob builders.
	PrintJob *PrintJobClient
	// Promotion is the client for interacting with the Promotion builders.
	Promotion *PromotionClient
	// PromotionApplication is the client for interacting with the PromotionApplication builders.
	PromotionApplication *PromotionApplicationClient
	// PromotionRedemption is the client for interacting with the PromotionRedemption builders.
	PromotionRedemption *PromotionRedemptionClient
	// PromotionRule is the client for interacting with the PromotionRule builders.
	PromotionRule *PromotionRuleClient
	// RateLimitConfig is the client for interacting with the RateLimitConfig builders.
	RateLimitConfig *RateLimitConfigClient
	// Referral is the client for interacting with the Referral builders.
	Referral *ReferralClient
	// RepairJob is the client for interacting with the RepairJob builders.
	RepairJob *RepairJobClient
	// RepairJobEvent is the client for interacting with the RepairJobEvent builders.
	RepairJobEvent *RepairJobEventClient
	// RepairJobPart is the client for interacting with the RepairJobPart builders.
	RepairJobPart *RepairJobPartClient
	// Resource is the client for interacting with the Resource builders.
	Resource *ResourceClient
	// Room is the client for interacting with the Room builders.
	Room *RoomClient
	// RoomAmenity is the client for interacting with the RoomAmenity builders.
	RoomAmenity *RoomAmenityClient
	// RoomAmenityAssignment is the client for interacting with the RoomAmenityAssignment builders.
	RoomAmenityAssignment *RoomAmenityAssignmentClient
	// RoomBooking is the client for interacting with the RoomBooking builders.
	RoomBooking *RoomBookingClient
	// RoomFolioItem is the client for interacting with the RoomFolioItem builders.
	RoomFolioItem *RoomFolioItemClient
	// RoomFolioPayment is the client for interacting with the RoomFolioPayment builders.
	RoomFolioPayment *RoomFolioPaymentClient
	// RoomGuest is the client for interacting with the RoomGuest builders.
	RoomGuest *RoomGuestClient
	// Section is the client for interacting with the Section builders.
	Section *SectionClient
	// SerialNumberLog is the client for interacting with the SerialNumberLog builders.
	SerialNumberLog *SerialNumberLogClient
	// ServiceConfig is the client for interacting with the ServiceConfig builders.
	ServiceConfig *ServiceConfigClient
	// ServicePackage is the client for interacting with the ServicePackage builders.
	ServicePackage *ServicePackageClient
	// ServicePackagePurchase is the client for interacting with the ServicePackagePurchase builders.
	ServicePackagePurchase *ServicePackagePurchaseClient
	// ServicePackageRedemption is the client for interacting with the ServicePackageRedemption builders.
	ServicePackageRedemption *ServicePackageRedemptionClient
	// ServiceQueueEntry is the client for interacting with the ServiceQueueEntry builders.
	ServiceQueueEntry *ServiceQueueEntryClient
	// ShiftRotation is the client for interacting with the ShiftRotation builders.
	ShiftRotation *ShiftRotationClient
	// ShiftRotationSlot is the client for interacting with the ShiftRotationSlot builders.
	ShiftRotationSlot *ShiftRotationSlotClient
	// StaffAdvance is the client for interacting with the StaffAdvance builders.
	StaffAdvance *StaffAdvanceClient
	// StaffMember is the client for interacting with the StaffMember builders.
	StaffMember *StaffMemberClient
	// StaffOutlet is the client for interacting with the StaffOutlet builders.
	StaffOutlet *StaffOutletClient
	// StaffPayroll is the client for interacting with the StaffPayroll builders.
	StaffPayroll *StaffPayrollClient
	// StaffPayrollLine is the client for interacting with the StaffPayrollLine builders.
	StaffPayrollLine *StaffPayrollLineClient
	// StaffPurchaseLink is the client for interacting with the StaffPurchaseLink builders.
	StaffPurchaseLink *StaffPurchaseLinkClient
	// StaffSchedule is the client for interacting with the StaffSchedule builders.
	StaffSchedule *StaffScheduleClient
	// StaffShiftOverride is the client for interacting with the StaffShiftOverride builders.
	StaffShiftOverride *StaffShiftOverrideClient
	// StockAlertSubscription is the client for interacting with the StockAlertSubscription builders.
	StockAlertSubscription *StockAlertSubscriptionClient
	// StockConsumptionEvent is the client for interacting with the StockConsumptionEvent builders.
	StockConsumptionEvent *StockConsumptionEventClient
	// SyncFailure is the client for interacting with the SyncFailure builders.
	SyncFailure *SyncFailureClient
	// Table is the client for interacting with the Table builders.
	Table *TableClient
	// TableAssignment is the client for interacting with the TableAssignment builders.
	TableAssignment *TableAssignmentClient
	// TableReservation is the client for interacting with the TableReservation builders.
	TableReservation *TableReservationClient
	// Tenant is the client for interacting with the Tenant builders.
	Tenant *TenantClient
	// TenantSyncEvent is the client for interacting with the TenantSyncEvent builders.
	TenantSyncEvent *TenantSyncEventClient
	// Tender is the client for interacting with the Tender builders.
	Tender *TenderClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserPOSRole is the client for interacting with the UserPOSRole builders.
	UserPOSRole *UserPOSRoleClient
	// WebhookDelivery is the client for interacting with the WebhookDelivery builders.
	WebhookDelivery *WebhookDeliveryClient
	// WebhookSubscription is the client for interacting with the WebhookSubscription builders.
	WebhookSubscription *WebhookSubscriptionClient
	// WeighingScaleReading is the client for interacting with the WeighingScaleReading builders.
	WeighingScaleReading *WeighingScaleReadingClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.Appointment = NewAppointmentClient(tx.config)
	tx.AuditLog = NewAuditLogClient(tx.config)
	tx.Backup = NewBackupClient(tx.config)
	tx.BackupSetting = NewBackupSettingClient(tx.config)
	tx.BarTab = NewBarTabClient(tx.config)
	tx.BarTabEvent = NewBarTabEventClient(tx.config)
	tx.BillSplit = NewBillSplitClient(tx.config)
	tx.CashDrawer = NewCashDrawerClient(tx.config)
	tx.CashDrawerEvent = NewCashDrawerEventClient(tx.config)
	tx.ChannelIntegration = NewChannelIntegrationClient(tx.config)
	tx.ChannelSyncJob = NewChannelSyncJobClient(tx.config)
	tx.ClientRecord = NewClientRecordClient(tx.config)
	tx.CommissionRecord = NewCommissionRecordClient(tx.config)
	tx.CommissionRule = NewCommissionRuleClient(tx.config)
	tx.CustomerBalanceCache = NewCustomerBalanceCacheClient(tx.config)
	tx.DailyClosing = NewDailyClosingClient(tx.config)
	tx.DocumentSequence = NewDocumentSequenceClient(tx.config)
	tx.EventBooking = NewEventBookingClient(tx.config)
	tx.Facility = NewFacilityClient(tx.config)
	tx.FacilityBooking = NewFacilityBookingClient(tx.config)
	tx.FeatureOverride = NewFeatureOverrideClient(tx.config)
	tx.GiftCard = NewGiftCardClient(tx.config)
	tx.GiftCardTransaction = NewGiftCardTransactionClient(tx.config)
	tx.HeldItem = NewHeldItemClient(tx.config)
	tx.HousekeepingTask = NewHousekeepingTaskClient(tx.config)
	tx.IdempotencyKey = NewIdempotencyKeyClient(tx.config)
	tx.IntegrationSetting = NewIntegrationSettingClient(tx.config)
	tx.InventorySnapshot = NewInventorySnapshotClient(tx.config)
	tx.KDSStation = NewKDSStationClient(tx.config)
	tx.KDSSyncFailure = NewKDSSyncFailureClient(tx.config)
	tx.KDSTicket = NewKDSTicketClient(tx.config)
	tx.LayawayPayment = NewLayawayPaymentClient(tx.config)
	tx.LayawayPlan = NewLayawayPlanClient(tx.config)
	tx.LeaveRequest = NewLeaveRequestClient(tx.config)
	tx.LicenseUsageSnapshot = NewLicenseUsageSnapshotClient(tx.config)
	tx.LoyaltyAccount = NewLoyaltyAccountClient(tx.config)
	tx.LoyaltyProgram = NewLoyaltyProgramClient(tx.config)
	tx.LoyaltyTransaction = NewLoyaltyTransactionClient(tx.config)
	tx.MealEntitlement = NewMealEntitlementClient(tx.config)
	tx.Modifier = NewModifierClient(tx.config)
	tx.ModifierGroup = NewModifierGroupClient(tx.config)
	tx.OrderLink = NewOrderLinkClient(tx.config)
	tx.OrderVoidCode = NewOrderVoidCodeClient(tx.config)
	tx.OutboxEvent = NewOutboxEventClient(tx.config)
	tx.Outlet = NewOutletClient(tx.config)
	tx.OutletSetting = NewOutletSettingClient(tx.config)
	tx.POSCatalogOverride = NewPOSCatalogOverrideClient(tx.config)
	tx.POSDevice = NewPOSDeviceClient(tx.config)
	tx.POSDeviceSession = NewPOSDeviceSessionClient(tx.config)
	tx.POSLineModifier = NewPOSLineModifierClient(tx.config)
	tx.POSOrder = NewPOSOrderClient(tx.config)
	tx.POSOrderEvent = NewPOSOrderEventClient(tx.config)
	tx.POSOrderLine = NewPOSOrderLineClient(tx.config)
	tx.POSPayment = NewPOSPaymentClient(tx.config)
	tx.POSPermission = NewPOSPermissionClient(tx.config)
	tx.POSRefund = NewPOSRefundClient(tx.config)
	tx.POSReturn = NewPOSReturnClient(tx.config)
	tx.POSReturnLine = NewPOSReturnLineClient(tx.config)
	tx.POSReversal = NewPOSReversalClient(tx.config)
	tx.POSRole = NewPOSRoleClient(tx.config)
	tx.POSRolePermission = NewPOSRolePermissionClient(tx.config)
	tx.POSRoleV2 = NewPOSRoleV2Client(tx.config)
	tx.POSSaleEdit = NewPOSSaleEditClient(tx.config)
	tx.POSSaleShred = NewPOSSaleShredClient(tx.config)
	tx.POSUserRoleAssignment = NewPOSUserRoleAssignmentClient(tx.config)
	tx.PosNotification = NewPosNotificationClient(tx.config)
	tx.PriceBook = NewPriceBookClient(tx.config)
	tx.PriceBookItem = NewPriceBookItemClient(tx.config)
	tx.PrintAgent = NewPrintAgentClient(tx.config)
	tx.PrintJob = NewPrintJobClient(tx.config)
	tx.Promotion = NewPromotionClient(tx.config)
	tx.PromotionApplication = NewPromotionApplicationClient(tx.config)
	tx.PromotionRedemption = NewPromotionRedemptionClient(tx.config)
	tx.PromotionRule = NewPromotionRuleClient(tx.config)
	tx.RateLimitConfig = NewRateLimitConfigClient(tx.config)
	tx.Referral = NewReferralClient(tx.config)
	tx.RepairJob = NewRepairJobClient(tx.config)
	tx.RepairJobEvent = NewRepairJobEventClient(tx.config)
	tx.RepairJobPart = NewRepairJobPartClient(tx.config)
	tx.Resource = NewResourceClient(tx.config)
	tx.Room = NewRoomClient(tx.config)
	tx.RoomAmenity = NewRoomAmenityClient(tx.config)
	tx.RoomAmenityAssignment = NewRoomAmenityAssignmentClient(tx.config)
	tx.RoomBooking = NewRoomBookingClient(tx.config)
	tx.RoomFolioItem = NewRoomFolioItemClient(tx.config)
	tx.RoomFolioPayment = NewRoomFolioPaymentClient(tx.config)
	tx.RoomGuest = NewRoomGuestClient(tx.config)
	tx.Section = NewSectionClient(tx.config)
	tx.SerialNumberLog = NewSerialNumberLogClient(tx.config)
	tx.ServiceConfig = NewServiceConfigClient(tx.config)
	tx.ServicePackage = NewServicePackageClient(tx.config)
	tx.ServicePackagePurchase = NewServicePackagePurchaseClient(tx.config)
	tx.ServicePackageRedemption = NewServicePackageRedemptionClient(tx.config)
	tx.ServiceQueueEntry = NewServiceQueueEntryClient(tx.config)
	tx.ShiftRotation = NewShiftRotationClient(tx.config)
	tx.ShiftRotationSlot = NewShiftRotationSlotClient(tx.config)
	tx.StaffAdvance = NewStaffAdvanceClient(tx.config)
	tx.StaffMember = NewStaffMemberClient(tx.config)
	tx.StaffOutlet = NewStaffOutletClient(tx.config)
	tx.StaffPayroll = NewStaffPayrollClient(tx.config)
	tx.StaffPayrollLine = NewStaffPayrollLineClient(tx.config)
	tx.StaffPurchaseLink = NewStaffPurchaseLinkClient(tx.config)
	tx.StaffSchedule = NewStaffScheduleClient(tx.config)
	tx.StaffShiftOverride = NewStaffShiftOverrideClient(tx.config)
	tx.StockAlertSubscription = NewStockAlertSubscriptionClient(tx.config)
	tx.StockConsumptionEvent = NewStockConsumptionEventClient(tx.config)
	tx.SyncFailure = NewSyncFailureClient(tx.config)
	tx.Table = NewTableClient(tx.config)
	tx.TableAssignment = NewTableAssignmentClient(tx.config)
	tx.TableReservation = NewTableReservationClient(tx.config)
	tx.Tenant = NewTenantClient(tx.config)
	tx.TenantSyncEvent = NewTenantSyncEventClient(tx.config)
	tx.Tender = NewTenderClient(tx.config)
	tx.User = NewUserClient(tx.config)
	tx.UserPOSRole = NewUserPOSRoleClient(tx.config)
	tx.WebhookDelivery = NewWebhookDeliveryClient(tx.config)
	tx.WebhookSubscription = NewWebhookSubscriptionClient(tx.config)
	tx.WeighingScaleReading = NewWeighingScaleReadingClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: Appointment.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)
