// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Appointment is the predicate function for appointment builders.
type Appointment func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Backup is the predicate function for backup builders.
type Backup func(*sql.Selector)

// BackupSetting is the predicate function for backupsetting builders.
type BackupSetting func(*sql.Selector)

// BarTab is the predicate function for bartab builders.
type BarTab func(*sql.Selector)

// BarTabEvent is the predicate function for bartabevent builders.
type BarTabEvent func(*sql.Selector)

// BillSplit is the predicate function for billsplit builders.
type BillSplit func(*sql.Selector)

// CashDrawer is the predicate function for cashdrawer builders.
type CashDrawer func(*sql.Selector)

// CashDrawerEvent is the predicate function for cashdrawerevent builders.
type CashDrawerEvent func(*sql.Selector)

// ChannelIntegration is the predicate function for channelintegration builders.
type ChannelIntegration func(*sql.Selector)

// ChannelSyncJob is the predicate function for channelsyncjob builders.
type ChannelSyncJob func(*sql.Selector)

// ClientRecord is the predicate function for clientrecord builders.
type ClientRecord func(*sql.Selector)

// CommissionRecord is the predicate function for commissionrecord builders.
type CommissionRecord func(*sql.Selector)

// CommissionRule is the predicate function for commissionrule builders.
type CommissionRule func(*sql.Selector)

// CustomerBalanceCache is the predicate function for customerbalancecache builders.
type CustomerBalanceCache func(*sql.Selector)

// DailyClosing is the predicate function for dailyclosing builders.
type DailyClosing func(*sql.Selector)

// DocumentSequence is the predicate function for documentsequence builders.
type DocumentSequence func(*sql.Selector)

// EventBooking is the predicate function for eventbooking builders.
type EventBooking func(*sql.Selector)

// Facility is the predicate function for facility builders.
type Facility func(*sql.Selector)

// FacilityBooking is the predicate function for facilitybooking builders.
type FacilityBooking func(*sql.Selector)

// FeatureOverride is the predicate function for featureoverride builders.
type FeatureOverride func(*sql.Selector)

// GiftCard is the predicate function for giftcard builders.
type GiftCard func(*sql.Selector)

// GiftCardTransaction is the predicate function for giftcardtransaction builders.
type GiftCardTransaction func(*sql.Selector)

// HeldItem is the predicate function for helditem builders.
type HeldItem func(*sql.Selector)

// HousekeepingTask is the predicate function for housekeepingtask builders.
type HousekeepingTask func(*sql.Selector)

// IdempotencyKey is the predicate function for idempotencykey builders.
type IdempotencyKey func(*sql.Selector)

// IntegrationSetting is the predicate function for integrationsetting builders.
type IntegrationSetting func(*sql.Selector)

// InventorySnapshot is the predicate function for inventorysnapshot builders.
type InventorySnapshot func(*sql.Selector)

// KDSStation is the predicate function for kdsstation builders.
type KDSStation func(*sql.Selector)

// KDSSyncFailure is the predicate function for kdssyncfailure builders.
type KDSSyncFailure func(*sql.Selector)

// KDSTicket is the predicate function for kdsticket builders.
type KDSTicket func(*sql.Selector)

// LayawayPayment is the predicate function for layawaypayment builders.
type LayawayPayment func(*sql.Selector)

// LayawayPlan is the predicate function for layawayplan builders.
type LayawayPlan func(*sql.Selector)

// LeaveRequest is the predicate function for leaverequest builders.
type LeaveRequest func(*sql.Selector)

// LicenseUsageSnapshot is the predicate function for licenseusagesnapshot builders.
type LicenseUsageSnapshot func(*sql.Selector)

// LoyaltyAccount is the predicate function for loyaltyaccount builders.
type LoyaltyAccount func(*sql.Selector)

// LoyaltyProgram is the predicate function for loyaltyprogram builders.
type LoyaltyProgram func(*sql.Selector)

// LoyaltyTransaction is the predicate function for loyaltytransaction builders.
type LoyaltyTransaction func(*sql.Selector)

// MealEntitlement is the predicate function for mealentitlement builders.
type MealEntitlement func(*sql.Selector)

// Modifier is the predicate function for modifier builders.
type Modifier func(*sql.Selector)

// ModifierGroup is the predicate function for modifiergroup builders.
type ModifierGroup func(*sql.Selector)

// OrderLink is the predicate function for orderlink builders.
type OrderLink func(*sql.Selector)

// OrderVoidCode is the predicate function for ordervoidcode builders.
type OrderVoidCode func(*sql.Selector)

// OutboxEvent is the predicate function for outboxevent builders.
type OutboxEvent func(*sql.Selector)

// Outlet is the predicate function for outlet builders.
type Outlet func(*sql.Selector)

// OutletSetting is the predicate function for outletsetting builders.
type OutletSetting func(*sql.Selector)

// POSCatalogOverride is the predicate function for poscatalogoverride builders.
type POSCatalogOverride func(*sql.Selector)

// POSDevice is the predicate function for posdevice builders.
type POSDevice func(*sql.Selector)

// POSDeviceSession is the predicate function for posdevicesession builders.
type POSDeviceSession func(*sql.Selector)

// POSLineModifier is the predicate function for poslinemodifier builders.
type POSLineModifier func(*sql.Selector)

// POSOrder is the predicate function for posorder builders.
type POSOrder func(*sql.Selector)

// POSOrderEvent is the predicate function for posorderevent builders.
type POSOrderEvent func(*sql.Selector)

// POSOrderLine is the predicate function for posorderline builders.
type POSOrderLine func(*sql.Selector)

// POSPayment is the predicate function for pospayment builders.
type POSPayment func(*sql.Selector)

// POSPermission is the predicate function for pospermission builders.
type POSPermission func(*sql.Selector)

// POSRefund is the predicate function for posrefund builders.
type POSRefund func(*sql.Selector)

// POSReturn is the predicate function for posreturn builders.
type POSReturn func(*sql.Selector)

// POSReturnLine is the predicate function for posreturnline builders.
type POSReturnLine func(*sql.Selector)

// POSReversal is the predicate function for posreversal builders.
type POSReversal func(*sql.Selector)

// POSRole is the predicate function for posrole builders.
type POSRole func(*sql.Selector)

// POSRolePermission is the predicate function for posrolepermission builders.
type POSRolePermission func(*sql.Selector)

// POSRoleV2 is the predicate function for posrolev2 builders.
type POSRoleV2 func(*sql.Selector)

// POSSaleEdit is the predicate function for possaleedit builders.
type POSSaleEdit func(*sql.Selector)

// POSSaleShred is the predicate function for possaleshred builders.
type POSSaleShred func(*sql.Selector)

// POSUserRoleAssignment is the predicate function for posuserroleassignment builders.
type POSUserRoleAssignment func(*sql.Selector)

// PosNotification is the predicate function for posnotification builders.
type PosNotification func(*sql.Selector)

// PriceBook is the predicate function for pricebook builders.
type PriceBook func(*sql.Selector)

// PriceBookItem is the predicate function for pricebookitem builders.
type PriceBookItem func(*sql.Selector)

// PrintAgent is the predicate function for printagent builders.
type PrintAgent func(*sql.Selector)

// PrintJob is the predicate function for printjob builders.
type PrintJob func(*sql.Selector)

// Promotion is the predicate function for promotion builders.
type Promotion func(*sql.Selector)

// PromotionApplication is the predicate function for promotionapplication builders.
type PromotionApplication func(*sql.Selector)

// PromotionRedemption is the predicate function for promotionredemption builders.
type PromotionRedemption func(*sql.Selector)

// PromotionRule is the predicate function for promotionrule builders.
type PromotionRule func(*sql.Selector)

// RateLimitConfig is the predicate function for ratelimitconfig builders.
type RateLimitConfig func(*sql.Selector)

// Referral is the predicate function for referral builders.
type Referral func(*sql.Selector)

// RepairJob is the predicate function for repairjob builders.
type RepairJob func(*sql.Selector)

// RepairJobEvent is the predicate function for repairjobevent builders.
type RepairJobEvent func(*sql.Selector)

// RepairJobPart is the predicate function for repairjobpart builders.
type RepairJobPart func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// RoomAmenity is the predicate function for roomamenity builders.
type RoomAmenity func(*sql.Selector)

// RoomAmenityAssignment is the predicate function for roomamenityassignment builders.
type RoomAmenityAssignment func(*sql.Selector)

// RoomBooking is the predicate function for roombooking builders.
type RoomBooking func(*sql.Selector)

// RoomFolioItem is the predicate function for roomfolioitem builders.
type RoomFolioItem func(*sql.Selector)

// RoomFolioPayment is the predicate function for roomfoliopayment builders.
type RoomFolioPayment func(*sql.Selector)

// RoomGuest is the predicate function for roomguest builders.
type RoomGuest func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// SerialNumberLog is the predicate function for serialnumberlog builders.
type SerialNumberLog func(*sql.Selector)

// ServiceConfig is the predicate function for serviceconfig builders.
type ServiceConfig func(*sql.Selector)

// ServicePackage is the predicate function for servicepackage builders.
type ServicePackage func(*sql.Selector)

// ServicePackagePurchase is the predicate function for servicepackagepurchase builders.
type ServicePackagePurchase func(*sql.Selector)

// ServicePackageRedemption is the predicate function for servicepackageredemption builders.
type ServicePackageRedemption func(*sql.Selector)

// ServiceQueueEntry is the predicate function for servicequeueentry builders.
type ServiceQueueEntry func(*sql.Selector)

// ShiftRotation is the predicate function for shiftrotation builders.
type ShiftRotation func(*sql.Selector)

// ShiftRotationSlot is the predicate function for shiftrotationslot builders.
type ShiftRotationSlot func(*sql.Selector)

// StaffAdvance is the predicate function for staffadvance builders.
type StaffAdvance func(*sql.Selector)

// StaffMember is the predicate function for staffmember builders.
type StaffMember func(*sql.Selector)

// StaffOutlet is the predicate function for staffoutlet builders.
type StaffOutlet func(*sql.Selector)

// StaffPayroll is the predicate function for staffpayroll builders.
type StaffPayroll func(*sql.Selector)

// StaffPayrollLine is the predicate function for staffpayrollline builders.
type StaffPayrollLine func(*sql.Selector)

// StaffPurchaseLink is the predicate function for staffpurchaselink builders.
type StaffPurchaseLink func(*sql.Selector)

// StaffSchedule is the predicate function for staffschedule builders.
type StaffSchedule func(*sql.Selector)

// StaffShiftOverride is the predicate function for staffshiftoverride builders.
type StaffShiftOverride func(*sql.Selector)

// StockAlertSubscription is the predicate function for stockalertsubscription builders.
type StockAlertSubscription func(*sql.Selector)

// StockConsumptionEvent is the predicate function for stockconsumptionevent builders.
type StockConsumptionEvent func(*sql.Selector)

// SyncFailure is the predicate function for syncfailure builders.
type SyncFailure func(*sql.Selector)

// Table is the predicate function for table builders.
type Table func(*sql.Selector)

// TableAssignment is the predicate function for tableassignment builders.
type TableAssignment func(*sql.Selector)

// TableReservation is the predicate function for tablereservation builders.
type TableReservation func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantSyncEvent is the predicate function for tenantsyncevent builders.
type TenantSyncEvent func(*sql.Selector)

// Tender is the predicate function for tender builders.
type Tender func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPOSRole is the predicate function for userposrole builders.
type UserPOSRole func(*sql.Selector)

// WebhookDelivery is the predicate function for webhookdelivery builders.
type WebhookDelivery func(*sql.Selector)

// WebhookSubscription is the predicate function for webhooksubscription builders.
type WebhookSubscription func(*sql.Selector)

// WeighingScaleReading is the predicate function for weighingscalereading builders.
type WeighingScaleReading func(*sql.Selector)
