// Code generated by ent, DO NOT EDIT.

package promotionredemption

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldTenantID, v))
}

// PromotionID applies equality check predicate on the "promotion_id" field. It's identical to PromotionIDEQ.
func PromotionID(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldPromotionID, v))
}

// CustomerKey applies equality check predicate on the "customer_key" field. It's identical to CustomerKeyEQ.
func CustomerKey(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldCustomerKey, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldOrderID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldQuantity, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLTE(FieldTenantID, v))
}

// PromotionIDEQ applies the EQ predicate on the "promotion_id" field.
func PromotionIDEQ(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldPromotionID, v))
}

// PromotionIDNEQ applies the NEQ predicate on the "promotion_id" field.
func PromotionIDNEQ(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNEQ(FieldPromotionID, v))
}

// PromotionIDIn applies the In predicate on the "promotion_id" field.
func PromotionIDIn(vs ...uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIn(FieldPromotionID, vs...))
}

// PromotionIDNotIn applies the NotIn predicate on the "promotion_id" field.
func PromotionIDNotIn(vs ...uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotIn(FieldPromotionID, vs...))
}

// PromotionIDGT applies the GT predicate on the "promotion_id" field.
func PromotionIDGT(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGT(FieldPromotionID, v))
}

// PromotionIDGTE applies the GTE predicate on the "promotion_id" field.
func PromotionIDGTE(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGTE(FieldPromotionID, v))
}

// PromotionIDLT applies the LT predicate on the "promotion_id" field.
func PromotionIDLT(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLT(FieldPromotionID, v))
}

// PromotionIDLTE applies the LTE predicate on the "promotion_id" field.
func PromotionIDLTE(v uuid.UUID) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLTE(FieldPromotionID, v))
}

// CustomerKeyEQ applies the EQ predicate on the "customer_key" field.
func CustomerKeyEQ(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldCustomerKey, v))
}

// CustomerKeyNEQ applies the NEQ predicate on the "customer_key" field.
func CustomerKeyNEQ(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNEQ(FieldCustomerKey, v))
}

// CustomerKeyIn applies the In predicate on the "customer_key" field.
func CustomerKeyIn(vs ...string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIn(FieldCustomerKey, vs...))
}

// CustomerKeyNotIn applies the NotIn predicate on the "customer_key" field.
func CustomerKeyNotIn(vs ...string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotIn(FieldCustomerKey, vs...))
}

// CustomerKeyGT applies the GT predicate on the "customer_key" field.
func CustomerKeyGT(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGT(FieldCustomerKey, v))
}

// CustomerKeyGTE applies the GTE predicate on the "customer_key" field.
func CustomerKeyGTE(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGTE(FieldCustomerKey, v))
}

// CustomerKeyLT applies the LT predicate on the "customer_key" field.
func CustomerKeyLT(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLT(FieldCustomerKey, v))
}

// CustomerKeyLTE applies the LTE predicate on the "customer_key" field.
func CustomerKeyLTE(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLTE(FieldCustomerKey, v))
}

// CustomerKeyContains applies the Contains predicate on the "customer_key" field.
func CustomerKeyContains(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldContains(FieldCustomerKey, v))
}

// CustomerKeyHasPrefix applies the HasPrefix predicate on the "customer_key" field.
func CustomerKeyHasPrefix(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldHasPrefix(FieldCustomerKey, v))
}

// CustomerKeyHasSuffix applies the HasSuffix predicate on the "customer_key" field.
func CustomerKeyHasSuffix(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldHasSuffix(FieldCustomerKey, v))
}

// CustomerKeyIsNil applies the IsNil predicate on the "customer_key" field.
func CustomerKeyIsNil() predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIsNull(FieldCustomerKey))
}

// CustomerKeyNotNil applies the NotNil predicate on the "customer_key" field.
func CustomerKeyNotNil() predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotNull(FieldCustomerKey))
}

// CustomerKeyEqualFold applies the EqualFold predicate on the "customer_key" field.
func CustomerKeyEqualFold(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEqualFold(FieldCustomerKey, v))
}

// CustomerKeyContainsFold applies the ContainsFold predicate on the "customer_key" field.
func CustomerKeyContainsFold(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldContainsFold(FieldCustomerKey, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v Channel) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v Channel) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...Channel) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...Channel) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotIn(FieldChannel, vs...))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldContainsFold(FieldOrderID, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v float64) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLTE(FieldQuantity, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromotionRedemption) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromotionRedemption) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromotionRedemption) predicate.PromotionRedemption {
	return predicate.PromotionRedemption(sql.NotPredicates(p))
}
