// Code generated by ent, DO NOT EDIT.

package promotion

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the promotion type in the database.
	Label = "promotion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldOutletID holds the string denoting the outlet_id field in the database.
	FieldOutletID = "outlet_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPromoCode holds the string denoting the promo_code field in the database.
	FieldPromoCode = "promo_code"
	// FieldPromoKind holds the string denoting the promo_kind field in the database.
	FieldPromoKind = "promo_kind"
	// FieldDaysOfWeek holds the string denoting the days_of_week field in the database.
	FieldDaysOfWeek = "days_of_week"
	// FieldWindowStart holds the string denoting the window_start field in the database.
	FieldWindowStart = "window_start"
	// FieldWindowEnd holds the string denoting the window_end field in the database.
	FieldWindowEnd = "window_end"
	// FieldAutoApply holds the string denoting the auto_apply field in the database.
	FieldAutoApply = "auto_apply"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartAt holds the string denoting the start_at field in the database.
	FieldStartAt = "start_at"
	// FieldEndAt holds the string denoting the end_at field in the database.
	FieldEndAt = "end_at"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldUsageLimit holds the string denoting the usage_limit field in the database.
	FieldUsageLimit = "usage_limit"
	// FieldMaxUnitsPerCustomer holds the string denoting the max_units_per_customer field in the database.
	FieldMaxUnitsPerCustomer = "max_units_per_customer"
	// Table holds the table name of the promotion in the database.
	Table = "promotions"
)

// Columns holds all SQL columns for promotion fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldOutletID,
	FieldName,
	FieldDescription,
	FieldPromoCode,
	FieldPromoKind,
	FieldDaysOfWeek,
	FieldWindowStart,
	FieldWindowEnd,
	FieldAutoApply,
	FieldStatus,
	FieldStartAt,
	FieldEndAt,
	FieldMetadata,
	FieldUsageLimit,
	FieldMaxUnitsPerCustomer,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultAutoApply holds the default value on creation for the "auto_apply" field.
	DefaultAutoApply bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultStartAt holds the default value on creation for the "start_at" field.
	DefaultStartAt func() time.Time
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]interface{}
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PromoKind defines the type for the "promo_kind" enum field.
type PromoKind string

// PromoKindCode is the default value of the PromoKind enum.
const DefaultPromoKind = PromoKindCode

// PromoKind values.
const (
	PromoKindCode      PromoKind = "code"
	PromoKindHappyHour PromoKind = "happy_hour"
	PromoKindAuto      PromoKind = "auto"
)

func (pk PromoKind) String() string {
	return string(pk)
}

// PromoKindValidator is a validator for the "promo_kind" field enum values. It is called by the builders before save.
func PromoKindValidator(pk PromoKind) error {
	switch pk {
	case PromoKindCode, PromoKindHappyHour, PromoKindAuto:
		return nil
	default:
		return fmt.Errorf("promotion: invalid enum value for promo_kind field: %q", pk)
	}
}

// OrderOption defines the ordering options for the Promotion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByOutletID orders the results by the outlet_id field.
func ByOutletID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutletID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPromoCode orders the results by the promo_code field.
func ByPromoCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromoCode, opts...).ToFunc()
}

// ByPromoKind orders the results by the promo_kind field.
func ByPromoKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromoKind, opts...).ToFunc()
}

// ByWindowStart orders the results by the window_start field.
func ByWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowStart, opts...).ToFunc()
}

// ByWindowEnd orders the results by the window_end field.
func ByWindowEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowEnd, opts...).ToFunc()
}

// ByAutoApply orders the results by the auto_apply field.
func ByAutoApply(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoApply, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStartAt orders the results by the start_at field.
func ByStartAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartAt, opts...).ToFunc()
}

// ByEndAt orders the results by the end_at field.
func ByEndAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndAt, opts...).ToFunc()
}

// ByUsageLimit orders the results by the usage_limit field.
func ByUsageLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLimit, opts...).ToFunc()
}

// ByMaxUnitsPerCustomer orders the results by the max_units_per_customer field.
func ByMaxUnitsPerCustomer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxUnitsPerCustomer, opts...).ToFunc()
}
