// Code generated by ent, DO NOT EDIT.

package promotion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldTenantID, v))
}

// OutletID applies equality check predicate on the "outlet_id" field. It's identical to OutletIDEQ.
func OutletID(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldOutletID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldDescription, v))
}

// PromoCode applies equality check predicate on the "promo_code" field. It's identical to PromoCodeEQ.
func PromoCode(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldPromoCode, v))
}

// WindowStart applies equality check predicate on the "window_start" field. It's identical to WindowStartEQ.
func WindowStart(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldWindowStart, v))
}

// WindowEnd applies equality check predicate on the "window_end" field. It's identical to WindowEndEQ.
func WindowEnd(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldWindowEnd, v))
}

// AutoApply applies equality check predicate on the "auto_apply" field. It's identical to AutoApplyEQ.
func AutoApply(v bool) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldAutoApply, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldStatus, v))
}

// StartAt applies equality check predicate on the "start_at" field. It's identical to StartAtEQ.
func StartAt(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldStartAt, v))
}

// EndAt applies equality check predicate on the "end_at" field. It's identical to EndAtEQ.
func EndAt(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldEndAt, v))
}

// UsageLimit applies equality check predicate on the "usage_limit" field. It's identical to UsageLimitEQ.
func UsageLimit(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldUsageLimit, v))
}

// MaxUnitsPerCustomer applies equality check predicate on the "max_units_per_customer" field. It's identical to MaxUnitsPerCustomerEQ.
func MaxUnitsPerCustomer(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldMaxUnitsPerCustomer, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldTenantID, v))
}

// OutletIDEQ applies the EQ predicate on the "outlet_id" field.
func OutletIDEQ(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldOutletID, v))
}

// OutletIDNEQ applies the NEQ predicate on the "outlet_id" field.
func OutletIDNEQ(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldOutletID, v))
}

// OutletIDIn applies the In predicate on the "outlet_id" field.
func OutletIDIn(vs ...uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldOutletID, vs...))
}

// OutletIDNotIn applies the NotIn predicate on the "outlet_id" field.
func OutletIDNotIn(vs ...uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldOutletID, vs...))
}

// OutletIDGT applies the GT predicate on the "outlet_id" field.
func OutletIDGT(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldOutletID, v))
}

// OutletIDGTE applies the GTE predicate on the "outlet_id" field.
func OutletIDGTE(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldOutletID, v))
}

// OutletIDLT applies the LT predicate on the "outlet_id" field.
func OutletIDLT(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldOutletID, v))
}

// OutletIDLTE applies the LTE predicate on the "outlet_id" field.
func OutletIDLTE(v uuid.UUID) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldOutletID, v))
}

// OutletIDIsNil applies the IsNil predicate on the "outlet_id" field.
func OutletIDIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldOutletID))
}

// OutletIDNotNil applies the NotNil predicate on the "outlet_id" field.
func OutletIDNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldOutletID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContainsFold(FieldDescription, v))
}

// PromoCodeEQ applies the EQ predicate on the "promo_code" field.
func PromoCodeEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldPromoCode, v))
}

// PromoCodeNEQ applies the NEQ predicate on the "promo_code" field.
func PromoCodeNEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldPromoCode, v))
}

// PromoCodeIn applies the In predicate on the "promo_code" field.
func PromoCodeIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldPromoCode, vs...))
}

// PromoCodeNotIn applies the NotIn predicate on the "promo_code" field.
func PromoCodeNotIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldPromoCode, vs...))
}

// PromoCodeGT applies the GT predicate on the "promo_code" field.
func PromoCodeGT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldPromoCode, v))
}

// PromoCodeGTE applies the GTE predicate on the "promo_code" field.
func PromoCodeGTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldPromoCode, v))
}

// PromoCodeLT applies the LT predicate on the "promo_code" field.
func PromoCodeLT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldPromoCode, v))
}

// PromoCodeLTE applies the LTE predicate on the "promo_code" field.
func PromoCodeLTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldPromoCode, v))
}

// PromoCodeContains applies the Contains predicate on the "promo_code" field.
func PromoCodeContains(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContains(FieldPromoCode, v))
}

// PromoCodeHasPrefix applies the HasPrefix predicate on the "promo_code" field.
func PromoCodeHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasPrefix(FieldPromoCode, v))
}

// PromoCodeHasSuffix applies the HasSuffix predicate on the "promo_code" field.
func PromoCodeHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasSuffix(FieldPromoCode, v))
}

// PromoCodeIsNil applies the IsNil predicate on the "promo_code" field.
func PromoCodeIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldPromoCode))
}

// PromoCodeNotNil applies the NotNil predicate on the "promo_code" field.
func PromoCodeNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldPromoCode))
}

// PromoCodeEqualFold applies the EqualFold predicate on the "promo_code" field.
func PromoCodeEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEqualFold(FieldPromoCode, v))
}

// PromoCodeContainsFold applies the ContainsFold predicate on the "promo_code" field.
func PromoCodeContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContainsFold(FieldPromoCode, v))
}

// PromoKindEQ applies the EQ predicate on the "promo_kind" field.
func PromoKindEQ(v PromoKind) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldPromoKind, v))
}

// PromoKindNEQ applies the NEQ predicate on the "promo_kind" field.
func PromoKindNEQ(v PromoKind) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldPromoKind, v))
}

// PromoKindIn applies the In predicate on the "promo_kind" field.
func PromoKindIn(vs ...PromoKind) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldPromoKind, vs...))
}

// PromoKindNotIn applies the NotIn predicate on the "promo_kind" field.
func PromoKindNotIn(vs ...PromoKind) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldPromoKind, vs...))
}

// DaysOfWeekIsNil applies the IsNil predicate on the "days_of_week" field.
func DaysOfWeekIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldDaysOfWeek))
}

// DaysOfWeekNotNil applies the NotNil predicate on the "days_of_week" field.
func DaysOfWeekNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldDaysOfWeek))
}

// WindowStartEQ applies the EQ predicate on the "window_start" field.
func WindowStartEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldWindowStart, v))
}

// WindowStartNEQ applies the NEQ predicate on the "window_start" field.
func WindowStartNEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldWindowStart, v))
}

// WindowStartIn applies the In predicate on the "window_start" field.
func WindowStartIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldWindowStart, vs...))
}

// WindowStartNotIn applies the NotIn predicate on the "window_start" field.
func WindowStartNotIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldWindowStart, vs...))
}

// WindowStartGT applies the GT predicate on the "window_start" field.
func WindowStartGT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldWindowStart, v))
}

// WindowStartGTE applies the GTE predicate on the "window_start" field.
func WindowStartGTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldWindowStart, v))
}

// WindowStartLT applies the LT predicate on the "window_start" field.
func WindowStartLT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldWindowStart, v))
}

// WindowStartLTE applies the LTE predicate on the "window_start" field.
func WindowStartLTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldWindowStart, v))
}

// WindowStartContains applies the Contains predicate on the "window_start" field.
func WindowStartContains(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContains(FieldWindowStart, v))
}

// WindowStartHasPrefix applies the HasPrefix predicate on the "window_start" field.
func WindowStartHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasPrefix(FieldWindowStart, v))
}

// WindowStartHasSuffix applies the HasSuffix predicate on the "window_start" field.
func WindowStartHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasSuffix(FieldWindowStart, v))
}

// WindowStartIsNil applies the IsNil predicate on the "window_start" field.
func WindowStartIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldWindowStart))
}

// WindowStartNotNil applies the NotNil predicate on the "window_start" field.
func WindowStartNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldWindowStart))
}

// WindowStartEqualFold applies the EqualFold predicate on the "window_start" field.
func WindowStartEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEqualFold(FieldWindowStart, v))
}

// WindowStartContainsFold applies the ContainsFold predicate on the "window_start" field.
func WindowStartContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContainsFold(FieldWindowStart, v))
}

// WindowEndEQ applies the EQ predicate on the "window_end" field.
func WindowEndEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldWindowEnd, v))
}

// WindowEndNEQ applies the NEQ predicate on the "window_end" field.
func WindowEndNEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldWindowEnd, v))
}

// WindowEndIn applies the In predicate on the "window_end" field.
func WindowEndIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldWindowEnd, vs...))
}

// WindowEndNotIn applies the NotIn predicate on the "window_end" field.
func WindowEndNotIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldWindowEnd, vs...))
}

// WindowEndGT applies the GT predicate on the "window_end" field.
func WindowEndGT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldWindowEnd, v))
}

// WindowEndGTE applies the GTE predicate on the "window_end" field.
func WindowEndGTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldWindowEnd, v))
}

// WindowEndLT applies the LT predicate on the "window_end" field.
func WindowEndLT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldWindowEnd, v))
}

// WindowEndLTE applies the LTE predicate on the "window_end" field.
func WindowEndLTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldWindowEnd, v))
}

// WindowEndContains applies the Contains predicate on the "window_end" field.
func WindowEndContains(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContains(FieldWindowEnd, v))
}

// WindowEndHasPrefix applies the HasPrefix predicate on the "window_end" field.
func WindowEndHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasPrefix(FieldWindowEnd, v))
}

// WindowEndHasSuffix applies the HasSuffix predicate on the "window_end" field.
func WindowEndHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasSuffix(FieldWindowEnd, v))
}

// WindowEndIsNil applies the IsNil predicate on the "window_end" field.
func WindowEndIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldWindowEnd))
}

// WindowEndNotNil applies the NotNil predicate on the "window_end" field.
func WindowEndNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldWindowEnd))
}

// WindowEndEqualFold applies the EqualFold predicate on the "window_end" field.
func WindowEndEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEqualFold(FieldWindowEnd, v))
}

// WindowEndContainsFold applies the ContainsFold predicate on the "window_end" field.
func WindowEndContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContainsFold(FieldWindowEnd, v))
}

// AutoApplyEQ applies the EQ predicate on the "auto_apply" field.
func AutoApplyEQ(v bool) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldAutoApply, v))
}

// AutoApplyNEQ applies the NEQ predicate on the "auto_apply" field.
func AutoApplyNEQ(v bool) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldAutoApply, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContainsFold(FieldStatus, v))
}

// StartAtEQ applies the EQ predicate on the "start_at" field.
func StartAtEQ(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldStartAt, v))
}

// StartAtNEQ applies the NEQ predicate on the "start_at" field.
func StartAtNEQ(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldStartAt, v))
}

// StartAtIn applies the In predicate on the "start_at" field.
func StartAtIn(vs ...time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldStartAt, vs...))
}

// StartAtNotIn applies the NotIn predicate on the "start_at" field.
func StartAtNotIn(vs ...time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldStartAt, vs...))
}

// StartAtGT applies the GT predicate on the "start_at" field.
func StartAtGT(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldStartAt, v))
}

// StartAtGTE applies the GTE predicate on the "start_at" field.
func StartAtGTE(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldStartAt, v))
}

// StartAtLT applies the LT predicate on the "start_at" field.
func StartAtLT(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldStartAt, v))
}

// StartAtLTE applies the LTE predicate on the "start_at" field.
func StartAtLTE(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldStartAt, v))
}

// EndAtEQ applies the EQ predicate on the "end_at" field.
func EndAtEQ(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldEndAt, v))
}

// EndAtNEQ applies the NEQ predicate on the "end_at" field.
func EndAtNEQ(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldEndAt, v))
}

// EndAtIn applies the In predicate on the "end_at" field.
func EndAtIn(vs ...time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldEndAt, vs...))
}

// EndAtNotIn applies the NotIn predicate on the "end_at" field.
func EndAtNotIn(vs ...time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldEndAt, vs...))
}

// EndAtGT applies the GT predicate on the "end_at" field.
func EndAtGT(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldEndAt, v))
}

// EndAtGTE applies the GTE predicate on the "end_at" field.
func EndAtGTE(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldEndAt, v))
}

// EndAtLT applies the LT predicate on the "end_at" field.
func EndAtLT(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldEndAt, v))
}

// EndAtLTE applies the LTE predicate on the "end_at" field.
func EndAtLTE(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldEndAt, v))
}

// EndAtIsNil applies the IsNil predicate on the "end_at" field.
func EndAtIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldEndAt))
}

// EndAtNotNil applies the NotNil predicate on the "end_at" field.
func EndAtNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldEndAt))
}

// UsageLimitEQ applies the EQ predicate on the "usage_limit" field.
func UsageLimitEQ(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldUsageLimit, v))
}

// UsageLimitNEQ applies the NEQ predicate on the "usage_limit" field.
func UsageLimitNEQ(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldUsageLimit, v))
}

// UsageLimitIn applies the In predicate on the "usage_limit" field.
func UsageLimitIn(vs ...int) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldUsageLimit, vs...))
}

// UsageLimitNotIn applies the NotIn predicate on the "usage_limit" field.
func UsageLimitNotIn(vs ...int) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldUsageLimit, vs...))
}

// UsageLimitGT applies the GT predicate on the "usage_limit" field.
func UsageLimitGT(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldUsageLimit, v))
}

// UsageLimitGTE applies the GTE predicate on the "usage_limit" field.
func UsageLimitGTE(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldUsageLimit, v))
}

// UsageLimitLT applies the LT predicate on the "usage_limit" field.
func UsageLimitLT(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldUsageLimit, v))
}

// UsageLimitLTE applies the LTE predicate on the "usage_limit" field.
func UsageLimitLTE(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldUsageLimit, v))
}

// UsageLimitIsNil applies the IsNil predicate on the "usage_limit" field.
func UsageLimitIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldUsageLimit))
}

// UsageLimitNotNil applies the NotNil predicate on the "usage_limit" field.
func UsageLimitNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldUsageLimit))
}

// MaxUnitsPerCustomerEQ applies the EQ predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerEQ(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldMaxUnitsPerCustomer, v))
}

// MaxUnitsPerCustomerNEQ applies the NEQ predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerNEQ(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldMaxUnitsPerCustomer, v))
}

// MaxUnitsPerCustomerIn applies the In predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerIn(vs ...int) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldMaxUnitsPerCustomer, vs...))
}

// MaxUnitsPerCustomerNotIn applies the NotIn predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerNotIn(vs ...int) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldMaxUnitsPerCustomer, vs...))
}

// MaxUnitsPerCustomerGT applies the GT predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerGT(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldMaxUnitsPerCustomer, v))
}

// MaxUnitsPerCustomerGTE applies the GTE predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerGTE(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldMaxUnitsPerCustomer, v))
}

// MaxUnitsPerCustomerLT applies the LT predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerLT(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldMaxUnitsPerCustomer, v))
}

// MaxUnitsPerCustomerLTE applies the LTE predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerLTE(v int) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldMaxUnitsPerCustomer, v))
}

// MaxUnitsPerCustomerIsNil applies the IsNil predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldMaxUnitsPerCustomer))
}

// MaxUnitsPerCustomerNotNil applies the NotNil predicate on the "max_units_per_customer" field.
func MaxUnitsPerCustomerNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldMaxUnitsPerCustomer))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(sql.NotPredicates(p))
}
