// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/bengobox/pos-service/internal/ent"
)

// The AppointmentFunc type is an adapter to allow the use of ordinary
// function as Appointment mutator.
type AppointmentFunc func(context.Context, *ent.AppointmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AppointmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AppointmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AppointmentMutation", m)
}

// The AuditLogFunc type is an adapter to allow the use of ordinary
// function as AuditLog mutator.
type AuditLogFunc func(context.Context, *ent.AuditLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AuditLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AuditLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AuditLogMutation", m)
}

// The BackupFunc type is an adapter to allow the use of ordinary
// function as Backup mutator.
type BackupFunc func(context.Context, *ent.BackupMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BackupFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BackupMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BackupMutation", m)
}

// The BackupSettingFunc type is an adapter to allow the use of ordinary
// function as BackupSetting mutator.
type BackupSettingFunc func(context.Context, *ent.BackupSettingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BackupSettingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BackupSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BackupSettingMutation", m)
}

// The BarTabFunc type is an adapter to allow the use of ordinary
// function as BarTab mutator.
type BarTabFunc func(context.Context, *ent.BarTabMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BarTabFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BarTabMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BarTabMutation", m)
}

// The BarTabEventFunc type is an adapter to allow the use of ordinary
// function as BarTabEvent mutator.
type BarTabEventFunc func(context.Context, *ent.BarTabEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BarTabEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BarTabEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BarTabEventMutation", m)
}

// The BillSplitFunc type is an adapter to allow the use of ordinary
// function as BillSplit mutator.
type BillSplitFunc func(context.Context, *ent.BillSplitMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BillSplitFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BillSplitMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BillSplitMutation", m)
}

// The CashDrawerFunc type is an adapter to allow the use of ordinary
// function as CashDrawer mutator.
type CashDrawerFunc func(context.Context, *ent.CashDrawerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CashDrawerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CashDrawerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CashDrawerMutation", m)
}

// The CashDrawerEventFunc type is an adapter to allow the use of ordinary
// function as CashDrawerEvent mutator.
type CashDrawerEventFunc func(context.Context, *ent.CashDrawerEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CashDrawerEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CashDrawerEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CashDrawerEventMutation", m)
}

// The ChannelIntegrationFunc type is an adapter to allow the use of ordinary
// function as ChannelIntegration mutator.
type ChannelIntegrationFunc func(context.Context, *ent.ChannelIntegrationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ChannelIntegrationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ChannelIntegrationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ChannelIntegrationMutation", m)
}

// The ChannelSyncJobFunc type is an adapter to allow the use of ordinary
// function as ChannelSyncJob mutator.
type ChannelSyncJobFunc func(context.Context, *ent.ChannelSyncJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ChannelSyncJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ChannelSyncJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ChannelSyncJobMutation", m)
}

// The ClientRecordFunc type is an adapter to allow the use of ordinary
// function as ClientRecord mutator.
type ClientRecordFunc func(context.Context, *ent.ClientRecordMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ClientRecordFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ClientRecordMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ClientRecordMutation", m)
}

// The CommissionRecordFunc type is an adapter to allow the use of ordinary
// function as CommissionRecord mutator.
type CommissionRecordFunc func(context.Context, *ent.CommissionRecordMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommissionRecordFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommissionRecordMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommissionRecordMutation", m)
}

// The CommissionRuleFunc type is an adapter to allow the use of ordinary
// function as CommissionRule mutator.
type CommissionRuleFunc func(context.Context, *ent.CommissionRuleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommissionRuleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommissionRuleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommissionRuleMutation", m)
}

// The CustomerBalanceCacheFunc type is an adapter to allow the use of ordinary
// function as CustomerBalanceCache mutator.
type CustomerBalanceCacheFunc func(context.Context, *ent.CustomerBalanceCacheMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CustomerBalanceCacheFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CustomerBalanceCacheMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CustomerBalanceCacheMutation", m)
}

// The DailyClosingFunc type is an adapter to allow the use of ordinary
// function as DailyClosing mutator.
type DailyClosingFunc func(context.Context, *ent.DailyClosingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DailyClosingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DailyClosingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DailyClosingMutation", m)
}

// The DocumentSequenceFunc type is an adapter to allow the use of ordinary
// function as DocumentSequence mutator.
type DocumentSequenceFunc func(context.Context, *ent.DocumentSequenceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DocumentSequenceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DocumentSequenceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DocumentSequenceMutation", m)
}

// The EventBookingFunc type is an adapter to allow the use of ordinary
// function as EventBooking mutator.
type EventBookingFunc func(context.Context, *ent.EventBookingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EventBookingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.EventBookingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EventBookingMutation", m)
}

// The FacilityFunc type is an adapter to allow the use of ordinary
// function as Facility mutator.
type FacilityFunc func(context.Context, *ent.FacilityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FacilityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FacilityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FacilityMutation", m)
}

// The FacilityBookingFunc type is an adapter to allow the use of ordinary
// function as FacilityBooking mutator.
type FacilityBookingFunc func(context.Context, *ent.FacilityBookingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FacilityBookingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FacilityBookingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FacilityBookingMutation", m)
}

// The FeatureOverrideFunc type is an adapter to allow the use of ordinary
// function as FeatureOverride mutator.
type FeatureOverrideFunc func(context.Context, *ent.FeatureOverrideMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FeatureOverrideFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FeatureOverrideMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FeatureOverrideMutation", m)
}

// The GiftCardFunc type is an adapter to allow the use of ordinary
// function as GiftCard mutator.
type GiftCardFunc func(context.Context, *ent.GiftCardMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GiftCardFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GiftCardMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GiftCardMutation", m)
}

// The GiftCardTransactionFunc type is an adapter to allow the use of ordinary
// function as GiftCardTransaction mutator.
type GiftCardTransactionFunc func(context.Context, *ent.GiftCardTransactionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GiftCardTransactionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GiftCardTransactionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GiftCardTransactionMutation", m)
}

// The HeldItemFunc type is an adapter to allow the use of ordinary
// function as HeldItem mutator.
type HeldItemFunc func(context.Context, *ent.HeldItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f HeldItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.HeldItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.HeldItemMutation", m)
}

// The HousekeepingTaskFunc type is an adapter to allow the use of ordinary
// function as HousekeepingTask mutator.
type HousekeepingTaskFunc func(context.Context, *ent.HousekeepingTaskMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f HousekeepingTaskFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.HousekeepingTaskMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.HousekeepingTaskMutation", m)
}

// The IdempotencyKeyFunc type is an adapter to allow the use of ordinary
// function as IdempotencyKey mutator.
type IdempotencyKeyFunc func(context.Context, *ent.IdempotencyKeyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f IdempotencyKeyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.IdempotencyKeyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.IdempotencyKeyMutation", m)
}

// The IntegrationSettingFunc type is an adapter to allow the use of ordinary
// function as IntegrationSetting mutator.
type IntegrationSettingFunc func(context.Context, *ent.IntegrationSettingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f IntegrationSettingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.IntegrationSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.IntegrationSettingMutation", m)
}

// The InventorySnapshotFunc type is an adapter to allow the use of ordinary
// function as InventorySnapshot mutator.
type InventorySnapshotFunc func(context.Context, *ent.InventorySnapshotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f InventorySnapshotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.InventorySnapshotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.InventorySnapshotMutation", m)
}

// The KDSStationFunc type is an adapter to allow the use of ordinary
// function as KDSStation mutator.
type KDSStationFunc func(context.Context, *ent.KDSStationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f KDSStationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.KDSStationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.KDSStationMutation", m)
}

// The KDSSyncFailureFunc type is an adapter to allow the use of ordinary
// function as KDSSyncFailure mutator.
type KDSSyncFailureFunc func(context.Context, *ent.KDSSyncFailureMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f KDSSyncFailureFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.KDSSyncFailureMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.KDSSyncFailureMutation", m)
}

// The KDSTicketFunc type is an adapter to allow the use of ordinary
// function as KDSTicket mutator.
type KDSTicketFunc func(context.Context, *ent.KDSTicketMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f KDSTicketFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.KDSTicketMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.KDSTicketMutation", m)
}

// The LayawayPaymentFunc type is an adapter to allow the use of ordinary
// function as LayawayPayment mutator.
type LayawayPaymentFunc func(context.Context, *ent.LayawayPaymentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LayawayPaymentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LayawayPaymentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LayawayPaymentMutation", m)
}

// The LayawayPlanFunc type is an adapter to allow the use of ordinary
// function as LayawayPlan mutator.
type LayawayPlanFunc func(context.Context, *ent.LayawayPlanMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LayawayPlanFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LayawayPlanMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LayawayPlanMutation", m)
}

// The LeaveRequestFunc type is an adapter to allow the use of ordinary
// function as LeaveRequest mutator.
type LeaveRequestFunc func(context.Context, *ent.LeaveRequestMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LeaveRequestFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LeaveRequestMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LeaveRequestMutation", m)
}

// The LicenseUsageSnapshotFunc type is an adapter to allow the use of ordinary
// function as LicenseUsageSnapshot mutator.
type LicenseUsageSnapshotFunc func(context.Context, *ent.LicenseUsageSnapshotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LicenseUsageSnapshotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LicenseUsageSnapshotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LicenseUsageSnapshotMutation", m)
}

// The LoyaltyAccountFunc type is an adapter to allow the use of ordinary
// function as LoyaltyAccount mutator.
type LoyaltyAccountFunc func(context.Context, *ent.LoyaltyAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LoyaltyAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LoyaltyAccountMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LoyaltyAccountMutation", m)
}

// The LoyaltyProgramFunc type is an adapter to allow the use of ordinary
// function as LoyaltyProgram mutator.
type LoyaltyProgramFunc func(context.Context, *ent.LoyaltyProgramMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LoyaltyProgramFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LoyaltyProgramMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LoyaltyProgramMutation", m)
}

// The LoyaltyTransactionFunc type is an adapter to allow the use of ordinary
// function as LoyaltyTransaction mutator.
type LoyaltyTransactionFunc func(context.Context, *ent.LoyaltyTransactionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LoyaltyTransactionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LoyaltyTransactionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LoyaltyTransactionMutation", m)
}

// The MealEntitlementFunc type is an adapter to allow the use of ordinary
// function as MealEntitlement mutator.
type MealEntitlementFunc func(context.Context, *ent.MealEntitlementMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MealEntitlementFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MealEntitlementMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MealEntitlementMutation", m)
}

// The ModifierFunc type is an adapter to allow the use of ordinary
// function as Modifier mutator.
type ModifierFunc func(context.Context, *ent.ModifierMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModifierFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModifierMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModifierMutation", m)
}

// The ModifierGroupFunc type is an adapter to allow the use of ordinary
// function as ModifierGroup mutator.
type ModifierGroupFunc func(context.Context, *ent.ModifierGroupMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModifierGroupFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModifierGroupMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModifierGroupMutation", m)
}

// The OrderLinkFunc type is an adapter to allow the use of ordinary
// function as OrderLink mutator.
type OrderLinkFunc func(context.Context, *ent.OrderLinkMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OrderLinkFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OrderLinkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OrderLinkMutation", m)
}

// The OrderVoidCodeFunc type is an adapter to allow the use of ordinary
// function as OrderVoidCode mutator.
type OrderVoidCodeFunc func(context.Context, *ent.OrderVoidCodeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OrderVoidCodeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OrderVoidCodeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OrderVoidCodeMutation", m)
}

// The OutboxEventFunc type is an adapter to allow the use of ordinary
// function as OutboxEvent mutator.
type OutboxEventFunc func(context.Context, *ent.OutboxEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OutboxEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OutboxEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OutboxEventMutation", m)
}

// The OutletFunc type is an adapter to allow the use of ordinary
// function as Outlet mutator.
type OutletFunc func(context.Context, *ent.OutletMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OutletFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OutletMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OutletMutation", m)
}

// The OutletSettingFunc type is an adapter to allow the use of ordinary
// function as OutletSetting mutator.
type OutletSettingFunc func(context.Context, *ent.OutletSettingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OutletSettingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OutletSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OutletSettingMutation", m)
}

// The POSCatalogOverrideFunc type is an adapter to allow the use of ordinary
// function as POSCatalogOverride mutator.
type POSCatalogOverrideFunc func(context.Context, *ent.POSCatalogOverrideMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSCatalogOverrideFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSCatalogOverrideMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSCatalogOverrideMutation", m)
}

// The POSDeviceFunc type is an adapter to allow the use of ordinary
// function as POSDevice mutator.
type POSDeviceFunc func(context.Context, *ent.POSDeviceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSDeviceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSDeviceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSDeviceMutation", m)
}

// The POSDeviceSessionFunc type is an adapter to allow the use of ordinary
// function as POSDeviceSession mutator.
type POSDeviceSessionFunc func(context.Context, *ent.POSDeviceSessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSDeviceSessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSDeviceSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSDeviceSessionMutation", m)
}

// The POSLineModifierFunc type is an adapter to allow the use of ordinary
// function as POSLineModifier mutator.
type POSLineModifierFunc func(context.Context, *ent.POSLineModifierMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSLineModifierFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSLineModifierMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSLineModifierMutation", m)
}

// The POSOrderFunc type is an adapter to allow the use of ordinary
// function as POSOrder mutator.
type POSOrderFunc func(context.Context, *ent.POSOrderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSOrderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSOrderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSOrderMutation", m)
}

// The POSOrderEventFunc type is an adapter to allow the use of ordinary
// function as POSOrderEvent mutator.
type POSOrderEventFunc func(context.Context, *ent.POSOrderEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSOrderEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSOrderEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSOrderEventMutation", m)
}

// The POSOrderLineFunc type is an adapter to allow the use of ordinary
// function as POSOrderLine mutator.
type POSOrderLineFunc func(context.Context, *ent.POSOrderLineMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSOrderLineFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSOrderLineMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSOrderLineMutation", m)
}

// The POSPaymentFunc type is an adapter to allow the use of ordinary
// function as POSPayment mutator.
type POSPaymentFunc func(context.Context, *ent.POSPaymentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSPaymentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSPaymentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSPaymentMutation", m)
}

// The POSPermissionFunc type is an adapter to allow the use of ordinary
// function as POSPermission mutator.
type POSPermissionFunc func(context.Context, *ent.POSPermissionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSPermissionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSPermissionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSPermissionMutation", m)
}

// The POSRefundFunc type is an adapter to allow the use of ordinary
// function as POSRefund mutator.
type POSRefundFunc func(context.Context, *ent.POSRefundMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSRefundFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSRefundMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSRefundMutation", m)
}

// The POSReturnFunc type is an adapter to allow the use of ordinary
// function as POSReturn mutator.
type POSReturnFunc func(context.Context, *ent.POSReturnMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSReturnFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSReturnMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSReturnMutation", m)
}

// The POSReturnLineFunc type is an adapter to allow the use of ordinary
// function as POSReturnLine mutator.
type POSReturnLineFunc func(context.Context, *ent.POSReturnLineMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSReturnLineFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSReturnLineMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSReturnLineMutation", m)
}

// The POSReversalFunc type is an adapter to allow the use of ordinary
// function as POSReversal mutator.
type POSReversalFunc func(context.Context, *ent.POSReversalMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSReversalFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSReversalMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSReversalMutation", m)
}

// The POSRoleFunc type is an adapter to allow the use of ordinary
// function as POSRole mutator.
type POSRoleFunc func(context.Context, *ent.POSRoleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSRoleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSRoleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSRoleMutation", m)
}

// The POSRolePermissionFunc type is an adapter to allow the use of ordinary
// function as POSRolePermission mutator.
type POSRolePermissionFunc func(context.Context, *ent.POSRolePermissionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSRolePermissionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSRolePermissionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSRolePermissionMutation", m)
}

// The POSRoleV2Func type is an adapter to allow the use of ordinary
// function as POSRoleV2 mutator.
type POSRoleV2Func func(context.Context, *ent.POSRoleV2Mutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSRoleV2Func) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSRoleV2Mutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSRoleV2Mutation", m)
}

// The POSSaleEditFunc type is an adapter to allow the use of ordinary
// function as POSSaleEdit mutator.
type POSSaleEditFunc func(context.Context, *ent.POSSaleEditMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSSaleEditFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSSaleEditMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSSaleEditMutation", m)
}

// The POSSaleShredFunc type is an adapter to allow the use of ordinary
// function as POSSaleShred mutator.
type POSSaleShredFunc func(context.Context, *ent.POSSaleShredMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSSaleShredFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSSaleShredMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSSaleShredMutation", m)
}

// The POSUserRoleAssignmentFunc type is an adapter to allow the use of ordinary
// function as POSUserRoleAssignment mutator.
type POSUserRoleAssignmentFunc func(context.Context, *ent.POSUserRoleAssignmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSUserRoleAssignmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSUserRoleAssignmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSUserRoleAssignmentMutation", m)
}

// The PosNotificationFunc type is an adapter to allow the use of ordinary
// function as PosNotification mutator.
type PosNotificationFunc func(context.Context, *ent.PosNotificationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PosNotificationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PosNotificationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PosNotificationMutation", m)
}

// The PriceBookFunc type is an adapter to allow the use of ordinary
// function as PriceBook mutator.
type PriceBookFunc func(context.Context, *ent.PriceBookMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PriceBookFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PriceBookMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PriceBookMutation", m)
}

// The PriceBookItemFunc type is an adapter to allow the use of ordinary
// function as PriceBookItem mutator.
type PriceBookItemFunc func(context.Context, *ent.PriceBookItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PriceBookItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PriceBookItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PriceBookItemMutation", m)
}

// The PrintAgentFunc type is an adapter to allow the use of ordinary
// function as PrintAgent mutator.
type PrintAgentFunc func(context.Context, *ent.PrintAgentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PrintAgentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PrintAgentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PrintAgentMutation", m)
}

// The PrintJobFunc type is an adapter to allow the use of ordinary
// function as PrintJob mutator.
type PrintJobFunc func(context.Context, *ent.PrintJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PrintJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PrintJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PrintJobMutation", m)
}

// The PromotionFunc type is an adapter to allow the use of ordinary
// function as Promotion mutator.
type PromotionFunc func(context.Context, *ent.PromotionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromotionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromotionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromotionMutation", m)
}

// The PromotionApplicationFunc type is an adapter to allow the use of ordinary
// function as PromotionApplication mutator.
type PromotionApplicationFunc func(context.Context, *ent.PromotionApplicationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromotionApplicationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromotionApplicationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromotionApplicationMutation", m)
}

// The PromotionRedemptionFunc type is an adapter to allow the use of ordinary
// function as PromotionRedemption mutator.
type PromotionRedemptionFunc func(context.Context, *ent.PromotionRedemptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromotionRedemptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromotionRedemptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromotionRedemptionMutation", m)
}

// The PromotionRuleFunc type is an adapter to allow the use of ordinary
// function as PromotionRule mutator.
type PromotionRuleFunc func(context.Context, *ent.PromotionRuleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromotionRuleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromotionRuleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromotionRuleMutation", m)
}

// The RateLimitConfigFunc type is an adapter to allow the use of ordinary
// function as RateLimitConfig mutator.
type RateLimitConfigFunc func(context.Context, *ent.RateLimitConfigMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RateLimitConfigFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RateLimitConfigMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RateLimitConfigMutation", m)
}

// The ReferralFunc type is an adapter to allow the use of ordinary
// function as Referral mutator.
type ReferralFunc func(context.Context, *ent.ReferralMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ReferralFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ReferralMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ReferralMutation", m)
}

// The RepairJobFunc type is an adapter to allow the use of ordinary
// function as RepairJob mutator.
type RepairJobFunc func(context.Context, *ent.RepairJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RepairJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RepairJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RepairJobMutation", m)
}

// The RepairJobEventFunc type is an adapter to allow the use of ordinary
// function as RepairJobEvent mutator.
type RepairJobEventFunc func(context.Context, *ent.RepairJobEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RepairJobEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RepairJobEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RepairJobEventMutation", m)
}

// The RepairJobPartFunc type is an adapter to allow the use of ordinary
// function as RepairJobPart mutator.
type RepairJobPartFunc func(context.Context, *ent.RepairJobPartMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RepairJobPartFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RepairJobPartMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RepairJobPartMutation", m)
}

// The ResourceFunc type is an adapter to allow the use of ordinary
// function as Resource mutator.
type ResourceFunc func(context.Context, *ent.ResourceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ResourceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ResourceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ResourceMutation", m)
}

// The RoomFunc type is an adapter to allow the use of ordinary
// function as Room mutator.
type RoomFunc func(context.Context, *ent.RoomMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoomFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoomMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoomMutation", m)
}

// The RoomAmenityFunc type is an adapter to allow the use of ordinary
// function as RoomAmenity mutator.
type RoomAmenityFunc func(context.Context, *ent.RoomAmenityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoomAmenityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoomAmenityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoomAmenityMutation", m)
}

// The RoomAmenityAssignmentFunc type is an adapter to allow the use of ordinary
// function as RoomAmenityAssignment mutator.
type RoomAmenityAssignmentFunc func(context.Context, *ent.RoomAmenityAssignmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoomAmenityAssignmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoomAmenityAssignmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoomAmenityAssignmentMutation", m)
}

// The RoomBookingFunc type is an adapter to allow the use of ordinary
// function as RoomBooking mutator.
type RoomBookingFunc func(context.Context, *ent.RoomBookingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoomBookingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoomBookingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoomBookingMutation", m)
}

// The RoomFolioItemFunc type is an adapter to allow the use of ordinary
// function as RoomFolioItem mutator.
type RoomFolioItemFunc func(context.Context, *ent.RoomFolioItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoomFolioItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoomFolioItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoomFolioItemMutation", m)
}

// The RoomFolioPaymentFunc type is an adapter to allow the use of ordinary
// function as RoomFolioPayment mutator.
type RoomFolioPaymentFunc func(context.Context, *ent.RoomFolioPaymentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoomFolioPaymentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoomFolioPaymentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoomFolioPaymentMutation", m)
}

// The RoomGuestFunc type is an adapter to allow the use of ordinary
// function as RoomGuest mutator.
type RoomGuestFunc func(context.Context, *ent.RoomGuestMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoomGuestFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoomGuestMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoomGuestMutation", m)
}

// The SectionFunc type is an adapter to allow the use of ordinary
// function as Section mutator.
type SectionFunc func(context.Context, *ent.SectionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SectionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SectionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SectionMutation", m)
}

// The SerialNumberLogFunc type is an adapter to allow the use of ordinary
// function as SerialNumberLog mutator.
type SerialNumberLogFunc func(context.Context, *ent.SerialNumberLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SerialNumberLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SerialNumberLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SerialNumberLogMutation", m)
}

// The ServiceConfigFunc type is an adapter to allow the use of ordinary
// function as ServiceConfig mutator.
type ServiceConfigFunc func(context.Context, *ent.ServiceConfigMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ServiceConfigFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ServiceConfigMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ServiceConfigMutation", m)
}

// The ServicePackageFunc type is an adapter to allow the use of ordinary
// function as ServicePackage mutator.
type ServicePackageFunc func(context.Context, *ent.ServicePackageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ServicePackageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ServicePackageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ServicePackageMutation", m)
}

// The ServicePackagePurchaseFunc type is an adapter to allow the use of ordinary
// function as ServicePackagePurchase mutator.
type ServicePackagePurchaseFunc func(context.Context, *ent.ServicePackagePurchaseMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ServicePackagePurchaseFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ServicePackagePurchaseMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ServicePackagePurchaseMutation", m)
}

// The ServicePackageRedemptionFunc type is an adapter to allow the use of ordinary
// function as ServicePackageRedemption mutator.
type ServicePackageRedemptionFunc func(context.Context, *ent.ServicePackageRedemptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ServicePackageRedemptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ServicePackageRedemptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ServicePackageRedemptionMutation", m)
}

// The ServiceQueueEntryFunc type is an adapter to allow the use of ordinary
// function as ServiceQueueEntry mutator.
type ServiceQueueEntryFunc func(context.Context, *ent.ServiceQueueEntryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ServiceQueueEntryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ServiceQueueEntryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ServiceQueueEntryMutation", m)
}

// The ShiftRotationFunc type is an adapter to allow the use of ordinary
// function as ShiftRotation mutator.
type ShiftRotationFunc func(context.Context, *ent.ShiftRotationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ShiftRotationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ShiftRotationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ShiftRotationMutation", m)
}

// The ShiftRotationSlotFunc type is an adapter to allow the use of ordinary
// function as ShiftRotationSlot mutator.
type ShiftRotationSlotFunc func(context.Context, *ent.ShiftRotationSlotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ShiftRotationSlotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ShiftRotationSlotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ShiftRotationSlotMutation", m)
}

// The StaffAdvanceFunc type is an adapter to allow the use of ordinary
// function as StaffAdvance mutator.
type StaffAdvanceFunc func(context.Context, *ent.StaffAdvanceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaffAdvanceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StaffAdvanceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaffAdvanceMutation", m)
}

// The StaffMemberFunc type is an adapter to allow the use of ordinary
// function as StaffMember mutator.
type StaffMemberFunc func(context.Context, *ent.StaffMemberMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaffMemberFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StaffMemberMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaffMemberMutation", m)
}

// The StaffOutletFunc type is an adapter to allow the use of ordinary
// function as StaffOutlet mutator.
type StaffOutletFunc func(context.Context, *ent.StaffOutletMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaffOutletFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StaffOutletMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaffOutletMutation", m)
}

// The StaffPayrollFunc type is an adapter to allow the use of ordinary
// function as StaffPayroll mutator.
type StaffPayrollFunc func(context.Context, *ent.StaffPayrollMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaffPayrollFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StaffPayrollMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaffPayrollMutation", m)
}

// The StaffPayrollLineFunc type is an adapter to allow the use of ordinary
// function as StaffPayrollLine mutator.
type StaffPayrollLineFunc func(context.Context, *ent.StaffPayrollLineMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaffPayrollLineFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StaffPayrollLineMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaffPayrollLineMutation", m)
}

// The StaffPurchaseLinkFunc type is an adapter to allow the use of ordinary
// function as StaffPurchaseLink mutator.
type StaffPurchaseLinkFunc func(context.Context, *ent.StaffPurchaseLinkMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaffPurchaseLinkFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StaffPurchaseLinkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaffPurchaseLinkMutation", m)
}

// The StaffScheduleFunc type is an adapter to allow the use of ordinary
// function as StaffSchedule mutator.
type StaffScheduleFunc func(context.Context, *ent.StaffScheduleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaffScheduleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StaffScheduleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaffScheduleMutation", m)
}

// The StaffShiftOverrideFunc type is an adapter to allow the use of ordinary
// function as StaffShiftOverride mutator.
type StaffShiftOverrideFunc func(context.Context, *ent.StaffShiftOverrideMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaffShiftOverrideFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StaffShiftOverrideMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaffShiftOverrideMutation", m)
}

// The StockAlertSubscriptionFunc type is an adapter to allow the use of ordinary
// function as StockAlertSubscription mutator.
type StockAlertSubscriptionFunc func(context.Context, *ent.StockAlertSubscriptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StockAlertSubscriptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StockAlertSubscriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StockAlertSubscriptionMutation", m)
}

// The StockConsumptionEventFunc type is an adapter to allow the use of ordinary
// function as StockConsumptionEvent mutator.
type StockConsumptionEventFunc func(context.Context, *ent.StockConsumptionEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StockConsumptionEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StockConsumptionEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StockConsumptionEventMutation", m)
}

// The SyncFailureFunc type is an adapter to allow the use of ordinary
// function as SyncFailure mutator.
type SyncFailureFunc func(context.Context, *ent.SyncFailureMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SyncFailureFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SyncFailureMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SyncFailureMutation", m)
}

// The TableFunc type is an adapter to allow the use of ordinary
// function as Table mutator.
type TableFunc func(context.Context, *ent.TableMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TableFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TableMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TableMutation", m)
}

// The TableAssignmentFunc type is an adapter to allow the use of ordinary
// function as TableAssignment mutator.
type TableAssignmentFunc func(context.Context, *ent.TableAssignmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TableAssignmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TableAssignmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TableAssignmentMutation", m)
}

// The TableReservationFunc type is an adapter to allow the use of ordinary
// function as TableReservation mutator.
type TableReservationFunc func(context.Context, *ent.TableReservationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TableReservationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TableReservationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TableReservationMutation", m)
}

// The TenantFunc type is an adapter to allow the use of ordinary
// function as Tenant mutator.
type TenantFunc func(context.Context, *ent.TenantMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TenantFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TenantMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TenantMutation", m)
}

// The TenantSyncEventFunc type is an adapter to allow the use of ordinary
// function as TenantSyncEvent mutator.
type TenantSyncEventFunc func(context.Context, *ent.TenantSyncEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TenantSyncEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TenantSyncEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TenantSyncEventMutation", m)
}

// The TenderFunc type is an adapter to allow the use of ordinary
// function as Tender mutator.
type TenderFunc func(context.Context, *ent.TenderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TenderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TenderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TenderMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// The UserPOSRoleFunc type is an adapter to allow the use of ordinary
// function as UserPOSRole mutator.
type UserPOSRoleFunc func(context.Context, *ent.UserPOSRoleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserPOSRoleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserPOSRoleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserPOSRoleMutation", m)
}

// The WebhookDeliveryFunc type is an adapter to allow the use of ordinary
// function as WebhookDelivery mutator.
type WebhookDeliveryFunc func(context.Context, *ent.WebhookDeliveryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WebhookDeliveryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WebhookDeliveryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WebhookDeliveryMutation", m)
}

// The WebhookSubscriptionFunc type is an adapter to allow the use of ordinary
// function as WebhookSubscription mutator.
type WebhookSubscriptionFunc func(context.Context, *ent.WebhookSubscriptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WebhookSubscriptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WebhookSubscriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WebhookSubscriptionMutation", m)
}

// The WeighingScaleReadingFunc type is an adapter to allow the use of ordinary
// function as WeighingScaleReading mutator.
type WeighingScaleReadingFunc func(context.Context, *ent.WeighingScaleReadingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WeighingScaleReadingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WeighingScaleReadingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WeighingScaleReadingMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
